Added a string based bitmap type for SVG
Mapsui/Mapsui pull request #1098
Opened 2021-03-12 10:29 UTC by charlenni

Added a string based bitmap type for SVG images.
Added a cache for Mapsui.Forms Pin type to save some memory, if always the same SVG or Pin color is used.

2021-03-12 12:33 UTC, janusw commented
The title sounds a bit odd, but after quickly glancing over your changes, I'd say I like what you're doing 😄

2021-03-14 16:45 UTC, tmijieux requested changes

2021-03-14 16:45 UTC, tmijieux commented on Mapsui.UI.Forms/Objects/Pin.cs
> +                    if (!string.IsNullOrEmpty(_bitmapIdKey))
unregistering a bitmapId is a bug, if multiple pins are already using the Id, that will leave all the other pins id hanging..., if the possibility of unregistering bitmap from the bitmap registry is absolutely needed here we need some kind of reference counting

2021-03-14 17:55 UTC, charlenni commented on Mapsui.UI.Forms/Objects/Pin.cs
> +                    if (!string.IsNullOrEmpty(_bitmapIdKey))
You are right. We should leave the bitmap in memory.

2021-03-14 21:04 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
As long as you only store svg data as string in the BitmapRegistry, this extra check is not really necessary, is it? From a performance perspective, it could be harmful ...

2021-03-15 09:57 UTC, tmijieux commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
i'd like something like `TrimStart().Substr(4).ToLower() == "<svg"` but there is the xml header problem

2021-03-15 10:28 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
My point is: Svgs are the only thing we store in BitmapRegistry as string right now. When they were stored as stream, we needed to check the content to distinguish them from other stream data (actual bitmaps). Now that should not be necessary any more, since the type of the stored object (string vs stream) is sufficient to make the distinction. Correct?

2021-03-15 10:30 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
And of course: `BitmapRegistry` -> `ImageRegistry`. I'm not saying all this renaming is absolutely necessary, but it might make things clearer and avoid confusion.

2021-03-15 12:06 UTC, charlenni commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
All this renaming breaks the existing code only for some smaller confusion.

2021-03-15 12:10 UTC, charlenni commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
To be correct: Svgs are the only thing we store **up to now** in BitmapRegistry as string. In the early times, there were only byte[] as type for bitmaps. Than other types arrive and additional checking was inserted. Now you say, that a string could only be a SVG image. But what, if someone diceide to add Base64 based images? They are represented as strings too.

2021-03-16 08:45 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
Well, it doesn't "break" anything. The `BitmapHelper` class should never show up in any user code, right?

Having a messed-up naming scheme in your private toy project is your own business, but for an open source project like Mapsui (which currently counts 37 contributors) a certain amount of code hygiene is kind of important.

Note that there is already a todo note in the `BitmapHelper` class about this topic ("Our BitmapRegistry stores not only bitmaps ..."). This really needs to be cleaned up at some point instead of adding to the confusion.

2021-03-16 08:52 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
Sure, once any other string-based data is added, the check is needed again. As long as this is not the case, it could be commented out. Is your Base64 example something that you expect to come soon, or is it more of a hypothetical possibility?

2021-03-16 09:08 UTC, charlenni commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
That's not correct. BitmapHelper is only hide by Mapsui.Forms. If you work direct with Features, you need to register bitmaps.

But ok, a renaming isn't a real problem for changes.

2021-03-18 21:21 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
Anyway, all this renaming does not need to be done here (can be handled in a follow-up issue).

2021-03-19 08:08 UTC, charlenni commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
No, I wouldn’t implement this in the moment. But do we remember this next time?

2021-03-19 08:21 UTC, charlenni commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
Ok, then I will revert this. But be sure, I will never do this again. I don’t create a PR for renaming a variable.

Btw. this is one of the reasons why the development of Mapsui is stagnating. If you shouldn’t change anything on the API and each PR should have only one or two lines, then there isn’t much more you can do beside removing bugs.

2021-03-19 10:08 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +        public static BitmapInfo LoadBitmap(object bitmapData)
> Ok, then I will revert this.

Revert what? `bitmapData` is still better than `bitmapStream`, so the renaming you've done already can certainly stay.

> But be sure, I will never do this again. I don’t create a PR for renaming a variable.

I think I will do exactly this: Open a PR for renaming all the things I listed above. You might say "it's just a name", but if there are a lot of wrong or misleading names, people make wrong assumptions when reading (and extending) the code, and that will lead to bugs. Again: I don't expect you to do this, but I think it's worth to fix it.


> Btw. this is one of the reasons why the development of Mapsui is stagnating. If you shouldn’t change anything on the API and each PR should have only one or two lines, then there isn’t much more you can do beside removing bugs.

I really don't get your point here:

- You were the one who complained that the renaming would break the API, and now complain that one cannot make any progress without breaking the API (that would have been my part 😉). What do you want: Make progress or keep the status quo?
- Who said that each PR should only have one or two lines? You created a PR that changes about 50 lines, I proposed even more changes. Where's the problem?

2021-03-19 10:14 UTC, janusw commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +                if (str.ToLower().Contains("<svg"))
> No, I wouldn’t implement this in the moment. But do we remember this next time?

I would just leave the commented-out check in the code (maybe with a comment), so that the next person who touches the `BitmapHelper` class has a chance to see that he might need to activate this check.

Anyway, I'm also fine with keeping the check, if you insist that it's necessary.

2021-04-09 10:50 UTC, pauldendulk approved these changes
I'll merge this and see if I can make some more changes. Perhaps the BitmapRegistry should have BitmapInfo objects as content. And since we are now still in alpha we can also afford some breaking changes by renames.

2021-04-09 10:50 UTC, merged