Added methods to make mass edit methods to LayerCollection
Mapsui/Mapsui pull request #1185
Opened 2021-08-31 22:23 UTC by Sebastian1989101

This methods can prevent lag issues when multiple layers are added/removed/modified on espacially iOS. Currently iOS makes a redraw for each add/remove which causes the app to lag heavily for multiple seconds.

2021-08-31 22:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Mapsui/Mapsui?pullRequest=1185) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Mapsui/Mapsui?pullRequest=1185) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Mapsui/Mapsui?pullRequest=1185) it.</sub>

2021-09-01 06:38 UTC, charlenni commented
Thank you for looking into this problem. It is only needed, because there is no order in the layer collection of Mapsui. So each time a layer is added, the Forms MapView has to remove it layers and add it again.

Isn't it possible two shorten the code? There are many functions, that are double and only the selection of the lists are different.

2021-09-01 09:50 UTC, Sebastian1989101 commented
@charlenni did some refactoring. The first version was just the mess I used personally in my iOS apps since a few weeks to prevent the lag as good as I could. 

About the MapView: I do not use it personally but does this not cause a memory leak by registering all the events but never unregister from them?

2021-09-01 13:59 UTC, inforithmics commented on Mapsui/Layers/LayerCollection.cs
> +        public delegate void MultipleLayersRemovedEventHandler(IEnumerable<ILayer> layers);
I think a generic Event Delegate should be used here

https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler-1?view=net-5.0

so the first parameter is the sender, and an Inherited EventArgs is added, where the layersRemoved, layersAdded are Properties.

So adding Additional Information doesn't break the Interafce

2021-09-01 20:03 UTC, inforithmics commented on Mapsui/Layers/LayerCollection.cs
> +        public delegate void MultipleLayersRemovedEventHandler(IEnumerable<ILayer> layers);
Sorry für the misunderstanding. I ment that if you want to add  additional parameters in the future it won't break\change the Event Signature. 

Yes changing it to the regular Event Layout would bei fine with me.

2021-09-01 20:20 UTC, Sebastian1989101 commented on Mapsui/Layers/LayerCollection.cs
> +        public delegate void MultipleLayersRemovedEventHandler(IEnumerable<ILayer> layers);
@inforithmics ah that makes sense. In thise case the other question would be if any event in the LayerCollection should change to have a uniform structure of the events. This however may break some users code if they already use the existing events. Because the events that affected single layers are already in there and only the events for multi layer edits are new.

2021-09-02 15:02 UTC, inforithmics commented on Mapsui/Layers/LayerCollection.cs
> +        public delegate void MultipleLayersRemovedEventHandler(IEnumerable<ILayer> layers);
I would leave the existing Events as is. If they need to change for good reason then the standart event structure should be used.

2021-09-02 16:39 UTC, inforithmics commented on Mapsui/Layers/LayerCollection.cs
> +        public event MultipleLayersModifiedEventHandler MultipleLayersModified;
Wouldn't it suffice to have only One Event MultipleLayersModified with the properties showing what was added and what was removed.

2021-09-02 16:42 UTC, inforithmics commented on Mapsui.UI.Forms/MapView.cs
> +            // Remove MapView layers
Shouldn't Here not the ModifyMultiple be used. So only one change is triggered instead of two.

2021-09-02 17:35 UTC, Sebastian1989101 commented on Mapsui.UI.Forms/MapView.cs
> +            // Remove MapView layers
This is just a wrapper to re-add the layers of the Forms Map. The content of this methods was previously just in the event call. Otherwise each event would need to remove and add the layers to the forms map like it was on the HandlerLayerChanged(ILayer layer) method before in this class. So this method was created in form of the refactoring that @charlenni suggested for this change.

2021-09-02 17:39 UTC, Sebastian1989101 commented on Mapsui/Layers/LayerCollection.cs
> +        public event MultipleLayersModifiedEventHandler MultipleLayersModified;
Yes, I would also prefer a single event with a EventArgs implementation used. However this would be different from the already existing methods. So either this will have two different event implementaiton layouts or each action has it's own event as it is right now. I think this is mostly something about personal preference. @pauldendulk added the single events long ago, so maybe there is a reason why it was done this way?

2021-09-02 17:53 UTC, inforithmics commented on Mapsui.UI.Forms/MapView.cs
> +            // Remove MapView layers
So that is good for me.

2021-09-02 20:24 UTC, inforithmics commented
I made a Performance Measurement and this patch Improved the Performance from.

<img width="705" alt="DisplayMapRenderLoop" src="https://user-images.githubusercontent.com/2290863/131910737-11ee8446-3a3b-4f58-a91b-8a5f60b55a01.PNG">

to

<img width="747" alt="DisplayLayerRemove" src="https://user-images.githubusercontent.com/2290863/131910810-5d06a9a3-acd5-487d-b314-2b3bec0427df.PNG">

So roughly 2.5 Times (This was tested against the Render Loop Patch, For this Measurement I merged the two patches)

2021-09-03 08:45 UTC, pauldendulk commented on Mapsui/Layers/LayerCollection.cs
> +        public event MultipleLayersModifiedEventHandler MultipleLayersModified;
@Sebastian1989101 @inforithmics I am not sure if I add the multiple event handlers or if it was based on some other existing component. It basically followed the customary pattern that was used back then (and maybe still is). 

 I am a big fan of reducing the amount of code. What about replacing all methods with just one? A single layer change could be sent as an array with one entry. Perhaps the arguments should also allow added and removed layers in one method. Perhaps the argument should have Added, Remove and Modified fields.

This is something that should not go in the upcoming release though, which should be due in a few weeks. Perhaps adding the methods like @Sebastian1989101 suggested is the best solution for now. It solves a actual performance problem. Some people will be working with the version for years.

A altered version could be committed shortly after the release.

Also we should take into account @charlenni's remark. A layer order should be added which should be independent from the order in the array.

2021-09-03 08:52 UTC, pauldendulk commented
@inforithmics How did you do the performance test?

2021-09-03 09:09 UTC, inforithmics commented
I normally use Jetbrains dotTrace. 
But you can although use the Visual Studio Profiler.
https://docs.microsoft.com/en-us/visualstudio/profiling/profiling-feature-tour?view=vs-2019

2021-09-03 13:12 UTC, Sebastian1989101 commented on Mapsui/Layers/LayerCollection.cs
> +        public event MultipleLayersModifiedEventHandler MultipleLayersModified;
@pauldendulk not the multiple but the event handlers for the single events. Thats why I have oriented the code to the same structure. 

Reducing the code is a good point. I got a suggestion from a friend on how to make all the new code work without adding new methods, which I have done before. I will make a new commit to this which will reduce this further without breaking any existing API for users of the current version of Mapsui.

2021-09-03 14:42 UTC, Sebastian1989101 commented
@inforithmics @pauldendulk I merged the Sinlge/Multi methods into one method with a params parameter. This way there are no API breaks while at the same time extending the existing stuff to be capable of taking more input at once. I also changed the events by removing all Mutli-Change events and just using one with a EventArgs parameter. Within the Mapsui Komponent this event is now used on no longer the single calls while at the same time the single events still exists for the users of Mapsui who already use them.

2021-09-04 05:55 UTC, inforithmics commented
Fantastic pull request. The Code looks now much cleaner and the interface supports now changes in the Layers handling like avoiding removing and readding them.

2021-09-04 05:56 UTC, inforithmics approved these changes

2021-09-04 07:05 UTC, pauldendulk requested changes

2021-09-04 07:05 UTC, pauldendulk commented on Mapsui/Layers/LayerCollectionChangedEventArgs.cs
> +    public class LayerCollectionChangedEventArgs : EventArgs
ah yes!, in line with what I suggested here https://github.com/Mapsui/Mapsui/pull/1185#discussion_r701715168

2021-09-04 07:05 UTC, pauldendulk commented on Mapsui/Layers/LayerCollection.cs
> +        public bool Remove(params ILayer[] layers)
This replaces the existing ```public bool Remove(ILayer layer)```. There is no need to introduce breaking changes in this phase. Let's keep all the existing methods and add an extra overloads for the new methods.

2021-09-04 08:31 UTC, Sebastian1989101 commented on Mapsui/Layers/LayerCollection.cs
> +        public bool Remove(params ILayer[] layers)
Would this really count as breaking change? Because it still works 1:1 as before. It can still be called with a single Layer like `Remove(new Layer());`. Thats why all unit tests are still working without any change to them.

2021-09-04 08:57 UTC, pauldendulk commented on Mapsui/Layers/LayerCollection.cs
> +        public bool Remove(params ILayer[] layers)
ah, because of the params keyword you could also enter a single layer. Nice solution!

2021-09-04 08:59 UTC, pauldendulk commented on Mapsui.UI.Forms/MapView.cs
> +            _mapControl.Map.Layers.Remove(MyLocationLayer, _mapCalloutLayer, _mapPinLayer, _mapDrawableLayer);
And here you can add multiple layers without wrapping them into an array. Another advantage of the params keyword.

2021-09-04 09:00 UTC, pauldendulk commented on Mapsui.UI.Forms/MapView.cs
> +            _mapControl.Map.Layers.Remove(MyLocationLayer, _mapCalloutLayer, _mapPinLayer, _mapDrawableLayer);
The only disadvantage is that you cannot pass in a List of IEnumerable without casting it to an array. If that is the primary use case that might be a reason to go for something else.

2021-09-04 10:18 UTC, Sebastian1989101 commented on Mapsui.UI.Forms/MapView.cs
> +            _mapControl.Map.Layers.Remove(MyLocationLayer, _mapCalloutLayer, _mapPinLayer, _mapDrawableLayer);
@pauldendulk the only way to make all kinds of enumerables work, is with a IEnumerable overload for each of those methods. I mean it would not add much code if it is prefered to give the user every option. So the question remains is, should I add those overloads?

2021-09-04 11:04 UTC, pauldendulk commented on Mapsui.UI.Forms/MapView.cs
> +            _mapControl.Map.Layers.Remove(MyLocationLayer, _mapCalloutLayer, _mapPinLayer, _mapDrawableLayer);
It is not clear if it is actually used that way. So, for now I would say there is no reason to add them.

2021-09-04 11:05 UTC, pauldendulk approved these changes
This is smart solution, adds needed functionality with little code.

2021-09-04 11:06 UTC, merged