Invalidate loop
Mapsui/Mapsui pull request #1192
Opened 2021-09-05 12:19 UTC by charlenni

A first shoot to use an invalidate loop to redraw MapControl. For this, more things are moved into the common MapControl. The interval of the loop could be changed and the loop could be started and stopped, if the control vanishes from screen.
`RefreshGraphics()` now only set a flag.

Should replace #1187

2021-09-05 12:35 UTC, janusw commented
Thanks for the update! Seems the CI is not quite happy with it, though:

```
Error: MapControl.cs(59,13): error CS0103: The name 'InternalInitialize' does not exist in the current context [/Users/runner/work/Mapsui/Mapsui/Mapsui.UI.Android/Mapsui.UI.Android.csproj]
Error: MapControl.cs(66,13): error CS0103: The name 'InternalInitialize' does not exist in the current context [/Users/runner/work/Mapsui/Mapsui/Mapsui.UI.Android/Mapsui.UI.Android.csproj]
Error: MapControl.cs(159,13): error CS0103: The name 'CommonPaintControl' does not exist in the current context [/Users/runner/work/Mapsui/Mapsui/Mapsui.UI.Android/Mapsui.UI.Android.csproj]
```

2021-09-05 12:38 UTC, janusw commented
And also:

```
Mapsui.UI.Shared\MapControl.cs(278,21): error CS0111: Type 'MapControl' already defines a member called 'RefreshGraphics' with the same parameter types [D:\a\Mapsui\Mapsui\Mapsui.UI.Uwp\Mapsui.UI.Uwp.csproj]
```

2021-09-05 14:06 UTC, charlenni commented
So, I hope now, that the basic problems are solved.

Should it be possible in the XAML renderer of WPF to check for the `PixelDensity`, then some more code could be moved to `CommonDrawControl()`.

In the current code, we don't distinguish between rendering and drawing. I think, that these are two different processes. But this is another issue.

2021-09-05 15:44 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +        public void StopUpdates()
Good method for static maps, saves rendering Time and Electricity

2021-09-05 15:45 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +            if (_drawing)
good condition if the previous rendering is still in progress

2021-09-05 15:48 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +        public int UpdateInterval
What happens if someone enters a negative number?

2021-09-05 15:50 UTC, inforithmics commented on Mapsui.UI.Wpf/MapControl.cs
> +                if (Dispatcher.CheckAccess()) InvalidateCanvas();
This guarantes that only a single thread is executed (the uithread of which there is only one)

2021-09-05 16:01 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +        public int UpdateInterval
Added a check.

2021-09-05 16:02 UTC, charlenni commented on Mapsui.UI.Wpf/MapControl.cs
> +                if (Dispatcher.CheckAccess()) InvalidateCanvas();
Was the same before. I didn't change anything in this part of the code.

2021-09-05 16:03 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +            if (_drawing)
I'm not sure, if we need a lock object. But I assume, that it is so fast, that there are no problems.

2021-09-05 16:05 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +        public void StopUpdates()
Do you think we need access to `_refresh`, `_drawing` or `_invalidate()` from outside?

2021-09-05 16:22 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +            _invalidate();
I tried out the branch and here it throws a null reference exception, Becuase ComminInitializer is first initialized and then the initializer.
in the Common Initializer the Timer is initialized and starts firing. But the _invalidate() is initialized in the Initialized so it can happen that a exception occours.

2021-09-05 16:25 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +        public void StopUpdates()
I cannot think of a use case yet.

2021-09-05 16:30 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +            Navigator.UpdateAnimations();
Maybe here could be the time measuresd and when it takes more than 16ms An Debug.Writline took more than (16ms) or a Trance.Writline(took more than 16 ms).

2021-09-05 16:47 UTC, inforithmics commented
I measured the Map Display time

From

![image](https://user-images.githubusercontent.com/2290863/132134593-5152d3aa-f7a6-43ba-9ce5-5073a5f8380e.png)

To

![image](https://user-images.githubusercontent.com/2290863/132134385-b002df48-e8a4-4b81-9912-99872e6200de.png)

so roughly a 400% performance improvement

2021-09-05 16:52 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +            _invalidate();
Solved

2021-09-05 16:55 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +            Navigator.UpdateAnimations();
This could be made at this point, but is not part of this PR. The next step would be to improve the performance of Mapsui. Up to now, we want to get rid of unneeded redrawing.

2021-09-05 16:59 UTC, charlenni commented
Is it possible to see the column headers? Would be nice. Thank you.

2021-09-05 17:04 UTC, charlenni commented
Is it possible to get the number of calls for `Mapsui.UI.Forms.MapControl.PaintSurface()`? In the first image it is around 4919.

2021-09-05 17:54 UTC, inforithmics commented
I updated the Performance comment

2021-09-05 18:25 UTC, charlenni commented
Thank you for the update.

That is strange. `PaintSurface` is called 13 times, while `VisibleFeatureIterator` is called 17 times. It seems, that the later one is also called from outside of the draw process. Have to look into this.

2021-09-05 21:49 UTC, inforithmics commented
The additional Renderings come from a RenderToBitmap for Rasterizing.

![image](https://user-images.githubusercontent.com/2290863/132142297-5fdd9fae-c49c-4246-a35e-1722e275908e.png)

2021-09-06 08:03 UTC, janusw commented
> For `UpdateInterval`, I'm missing a corresponding property in the MapView, otherwise it cannot be set when using a MapView (same for `StartUpdates` and `StopUpdates`).

I added these in my fork: https://github.com/janusw/Mapsui/commits/InvalidateLoop

Feel free to include it into this PR if you agree!

2021-09-06 09:06 UTC, charlenni commented
This is the answer on the last comment of @pauldendulk on #1092, which is closed.

Yes, we have to do this and that. And yes, there are hundreds of ways to improve the performance. But all this isn‘t discussed here.

This discussion is about reducing the redraws of the screen. It is about the fact, that in the moment each change of anything triggers a redraw of the screen. To get rid of this, we have to collect such redraws. But what is the correct way to do this? This approach waits a given amount of milliseconds and than, if there is something to draw, updates the screen.

So the question is:
1. Do we accept the need of such a collection?
2. Do we think, this approach could work?
3. Do we have a better approach for this?

2021-09-06 10:14 UTC, janusw commented
> This discussion is about reducing the redraws of the screen. It is about the fact, that in the moment each change of anything triggers a redraw of the screen. To get rid of this, we have to collect such redraws. But what is the correct way to do this? This approach waits a given amount of milliseconds and than, if there is something to draw, updates the screen.
> 
> So the question is:
> 
>     1. Do we accept the need of such a collection?

From my point of view: Clearly YES!

The current scheme of redrawing the map everytime something changes simply does not scale well to complex scenarios. I can show you some where the changes here make a hell of a difference.

As an example, think of a map with a large number of pins (order of magnitude: hundreds or thousands), each of which is updated regularly. The current Mapsui fails badly on such a scenario (completely unusable, in particular on iOS), and this branch gives phenomenal improvements.

It seems @inforithmics has more relevant use cases.

>     2. Do we think, this approach could work?

It sounds very reasonable to me (in theory), and also in practice I can confirm that it greatly improves the responsiveness of the map for scenarios like the one described above. So yes, it works!


>     3. Do we have a better approach for this?

I don't have a much better idea right now. Having a configurable update interval is a good idea, and also the methods `StartUpdates` and `StopUpdates` are pretty useful, since they avoid wasting time on complex rendering if the map is not being displayed at all.


IMHO we should clearly go ahead with this. Further performance improvements can certainly be added later, but should not be subject of this PR.

2021-09-06 10:53 UTC, charlenni commented
BTW I assume that this PR nothing change at the FPS. It stops the rate at around 60 FPS (1000 ms/16 ms). But in the moment the FPS is limited by the time `CommonDrawControl()` needs. So, if we want to increase the FPS, we have to improve this part. This PR is only for reactiveness of the control.

2021-09-06 11:31 UTC, charlenni commented
And if I interpret the performance diagram of @inforithmics correct, then we could draw the map 13 times in a second, which leads to 13 FPS, correct?

Opposite to the last proposal, this hasn't a calculation for FPS. This should go in the next step into `CommonDrawControl()`. Should be the next PR.

2021-09-06 13:36 UTC, charlenni commented
Perhaps a `ForceUpdate()` could be helpful in scenarios, where you want to have a static map that should be redrawn after the initial configuration. It invalidates the screen once.

2021-09-06 13:56 UTC, janusw commented
> Perhaps a `ForceUpdate()` could be helpful in scenarios, where you want to have a static map that should be redrawn after the initial configuration. It invalidates the screen once.

Might possibly be useful and is trivial to implement. (I personally don't have a use case for this, though.)

@charlenni Could you please push your MapView changes (or merge mine from https://github.com/janusw/Mapsui/commit/bfe05ed93848d28947c34fdb3aec099dacd3578f), please?

2021-09-06 16:28 UTC, charlenni commented
@janusw Sorry for the delay. I'm still on vacation, and it isn't so easy to find a WiFi to upload the changes ;-)

2021-09-06 16:35 UTC, charlenni commented
@inforithmics If you now compare the performance of Mapsui, you should post the values for `CommonDrawControl()`. That are the times, that the control needs to draw its content. The `Time`and `Calls`. First divided by the second will give a mean drawing time. Correct?

2021-09-06 17:41 UTC, janusw commented
> @janusw Sorry for the delay. I'm still on vacation, and it isn't so easy to find a WiFi to upload the changes ;-)

Nevermind (also: thanks!). You were posting all days, so I thought you were available. Enjoy your vacation!

2021-09-06 17:48 UTC, charlenni commented
All possible with the smartphone, but no PR changes.

2021-09-06 17:52 UTC, janusw commented on Mapsui.UI.Forms/MapView.cs
> +        public void StartUpdates(bool refresh)
The parameter should probably have a default value here (as in the corresponding MapControl method).

2021-09-06 18:14 UTC, charlenni commented
Did I said that I hate the MapView construction? All this wrappers. Perhaps I should make the buttons as widgets.

2021-09-06 18:22 UTC, janusw commented
> Did I said that I hate the MapView construction? All this wrappers.

Certainly not very elegant. Wasn't there the idea to make MapView inherit from MapControl? Is that feasible? At least it would remove the need for these kinds of wrappers ...

2021-09-06 18:26 UTC, janusw requested changes

2021-09-06 18:26 UTC, janusw commented on Mapsui.UI.Forms/MapView.cs
> +        public int UpdateInterval => _mapControl.UpdateInterval;
This is not the proper syntax apparently. When I try to assign to MapView.UpdateInterval, I get:
`Error CS0200: Property or indexer 'MapView.UpdateInterval' cannot be assigned to -- it is read only (CS0200)`

2021-09-06 19:25 UTC, charlenni commented on Mapsui.UI.Forms/MapView.cs
> +        public int UpdateInterval => _mapControl.UpdateInterval;
Hopefully solved

2021-09-07 08:52 UTC, janusw commented on Mapsui.UI.Forms/MapView.cs
> +        public int UpdateInterval => _mapControl.UpdateInterval;
Think so.

2021-09-07 08:55 UTC, janusw approved these changes
I am happy with the PR at this point. I gives huge performance improvements for some of my use cases. Thanks for the great work, @charlenni !

If @pauldendulk and @inforithmics are ok with it as well, I hope we can merge this very soon.

2021-09-07 14:30 UTC, inforithmics approved these changes

2021-09-07 20:53 UTC, janusw commented
Alright, we have two approvals here. @pauldendulk Do you have any further comments, or can I merge this?

2021-09-08 07:30 UTC, pauldendulk commented
> Alright, we have two approvals here. @pauldendulk Do you have any further comments, or can I merge this?

I'll would like to have a look at it later this week.

2021-09-08 07:43 UTC, janusw commented
> I'll would like to have a look at it later this week.

Sure, take your time! (I have to admit that this issue is kind of urgent on my side, but of course I understand that you want to have a proper look at it.)

I guess this PR would be a good topic for a meeting on Friday (if we manage to have one this week) ...

2021-09-10 12:38 UTC, pauldendulk commented
> Should it be possible in the XAML renderer of WPF to check for the PixelDensity, then some more code could be moved to CommonDrawControl().

There is a method to get the PixelDensity for WPF, so I think this should be possible. Or are you saying there is problem with this code? (see Mapsui.UI.Wpf.MapControl.GetPixelDensity())

It would be nice if it could be moved but perhaps an exception would occur on ```canvas.Scale(PixelDensity, PixelDensity);``` if it is zero.

2021-09-10 12:45 UTC, pauldendulk commented
Is there a general way in which this could be tested? Which project did you run? Is there a sample for this? Of not there should be (not part of this PR). Perhaps based on @bertt's [sample](https://github.com/Mapsui/Mapsui/tree/bug/getfeaturesinview_not_called/Samples/Mapsui.Samples.MemoryProvider/MemoryProvider/).

2021-09-10 13:16 UTC, charlenni commented
How should this be made testable? BTW did we tested the way before?

2021-09-10 13:46 UTC, charlenni commented
To be correct: it is a visible control like a button. So how to test it? There is a tool from Xamarin, where you could test such things in many, many devices. But it costs.

2021-09-10 14:18 UTC, pauldendulk commented
I was merely asking which project I should run in order to see the performance problem so I could see how it is affected by the patch. 

But on the topic. It is possible to unit test the individual parts. A invalidate loop could be in een separate class that could be tested. This is hard because it is a process over time, but it still possible. That fact that we did not have much tests in the past does not mean we should not add it in the future.

2021-09-10 14:58 UTC, pauldendulk commented
I will merge this PR.

I had some hesitation because the underlying problem is in the platform and was thinking about a solution that is closer to the platform. 

All these platforms have a method called Invalidate or SetNeedsDisplay. These methods have names like these because they should not do a direct call to the OnPaint method. They should set a flag to like the '_refresh' flag in this PR. And ideally the platform implementation should also have a way to cap the framerate. Apparently this is not what is happening.

A solution I was thinking of was to fix this in the OnPaint method. Here we could use a Thread.Sleep to cap the framerate. In that way it is also easier to avoid overlap in calls (if the paint itself takes more than 16 ms).  A problem with Thread.Sleep is however that it locks the thread, which could be problematic as well. Not something I want to investigate now.

This PR solves a problem which probably hits many users. Thanks a lot for this contribution @charlenni!

2021-09-10 15:00 UTC, merged

2021-09-10 15:13 UTC, charlenni commented
You can use any sample that uses a MapControl on any platform. Because it is the same for all platforms. It seems that the most problems are on iOS. Use a sample that changes the map often.

2021-09-10 17:56 UTC, charlenni commented
If we make a solution for each platform, then the code is getting complicated. I thought about a method, so we could handle this problem on all platforms in the same way.

We could have made it on Android totally different. It seems, that Android could handle this by itself. But than we had to do it for the Forms or Maui platform also separate for each platform, what needs many #if in the code.

So I chooses a way, which is the same on all platforms, make it better on some of them and doesn't make it worth on others.

If we find better solution in the future, it isn't a problem to change this.

BTW it is problematic in the OnPaint event, because you don't know, if the redraw is called because something on the map has changed which could wait or if the control reappears on the screen and needs an immediate redraw.

2021-09-13 07:09 UTC, pauldendulk commented
> If we make a solution for each platform, then the code is getting complicated. I thought about a method, so we could handle this problem on all platforms in the same way.

I imagined a generic solution with code placed in a shared class which is called from all implementations like the CommonDrawControl. But perhaps you are right and we should take platform differences into account. With that in mind I really would like to have more statistics.