Nullable fixes
Mapsui/Mapsui pull request #1383
Opened 2021-11-13 17:04 UTC by inforithmics

Some more nullable fixes mostly in the sample projects

2021-11-14 04:57 UTC, pauldendulk commented on Mapsui.Core/INavigator.cs
> +        void NavigateTo(MRect? extent, ScaleMethod scaleMethod = ScaleMethod.Fit, long duration = 0, Easing? easing = default);
In a future version this should perhaps be non-nullable. We will need to avoid possible null calls. Perhaps the Home method should only be called if Extent is not null and send the Extent as separate parameter and not as part of the IViewport.Extent (because the IViewport.Extent can be null during startup).

2021-11-14 05:00 UTC, pauldendulk commented on Mapsui.Core/Layers/AnimatedFeatures.cs
> +            Debug.WriteLine("Trackee: " + item.Feature?["Trackee"]);
If feature is null this will write eight lines of useless information. Better to check earlier.

But then again. This whole logging should be removed anyway.

2021-11-14 05:03 UTC, pauldendulk commented on Mapsui.Core/MRaster.cs
> +        public MRaster(MRaster? raster) : base(raster.Min.X, raster.Min.Y, raster.Max.X, raster.Max.Y)
I am still on the fence about this one. It complicates a lot of code of we allow the data of the feature to be null. 

Somewhere else I said it was complicated because a Geometry can be Empty, but perhaps we should consider that corrupt data.

2021-11-14 05:04 UTC, pauldendulk commented on Mapsui.Core/Providers/IProvider.cs
> +        string? CRS { get; set; }
CRS null too? Do you think that is a good idea?

2021-11-14 05:18 UTC, pauldendulk commented on Mapsui.Core/Styles/LabelStyle.cs
> +        public Brush? BackColor { get; set; } // todo: rename
Here too everything null?

2021-11-14 05:28 UTC, pauldendulk requested changes
All these changes are only in one direction, making everything nullable. While we would like to go in the other direction. Code will become simpler if we do not allow null and throw early if users do. Now the code if full of line like `if (variable = null) return;` This will prevent the warnings in visual studio but could result in behavior that users do not understand. Users write some code and then nothing happens and you see nothing. That is hard to debug. Perhaps it is not possible to make fields non-nullable, but at least we should investigate the possibility and perhaps rewrite some code to make it possible. If we remove all these warnings in our code by adding null checks everywhere I am afraid we will lose an opportunity to actually make it better.

I am not sure how to go forward with this. I think there should be more discussion about individual changes. Perhaps we should create more issues to discuss it.

2021-11-14 20:11 UTC, inforithmics commented
I'll improve this pullrequest with the Suggestions.
The method I used ist that I'll fix the warnings for example a property ist not initialized in the constructor and therefore nullable. Or a property is Set to null and therfore nullable too. This is the reason why I fixed the nullable warnings in the samples first because it demonstrates the usage of the library.

2021-11-14 20:24 UTC, inforithmics commented on Mapsui.Core/Providers/IProvider.cs
> +        string? CRS { get; set; }
No I don't think this is a good idea. I'll research where this is Set or not Set.

2021-11-14 20:25 UTC, inforithmics commented on Mapsui.Core/Styles/LabelStyle.cs
> +        public Brush? BackColor { get; set; } // todo: rename
Should I'll allow Setting to null and choose the transparent back color when Setting it to null.

2021-11-14 20:26 UTC, inforithmics commented on Mapsui.Core/MRaster.cs
> +        public MRaster(MRaster? raster) : base(raster.Min.X, raster.Min.Y, raster.Max.X, raster.Max.Y)
I'll Set it to non nullable and will fix it are the call sites and throw an exception if it is still null

2021-11-14 20:27 UTC, inforithmics commented on Mapsui.Core/Layers/AnimatedFeatures.cs
> +            Debug.WriteLine("Trackee: " + item.Feature?["Trackee"]);
Good point

2021-11-14 20:40 UTC, inforithmics commented on Mapsui.Core/INavigator.cs
> +        void NavigateTo(MRect? extent, ScaleMethod scaleMethod = ScaleMethod.Fit, long duration = 0, Easing? easing = default);
I Made this null to avoid to Check for null in the calling sites. But good point

2021-11-24 05:57 UTC, pauldendulk commented
It's difficult. I really would like to make more non-nullable but every time I think deeper I start doubting if it is possible, or should be null. Perhaps I should not be picky in this phase and just accept the choices you make. Every single choice could take a lot of attention.

2021-11-24 05:57 UTC, pauldendulk approved these changes

2021-11-24 05:57 UTC, merged