More disposable fixes
Mapsui/Mapsui pull request #1420
Opened 2021-12-11 21:12 UTC by inforithmics

2021-12-12 13:03 UTC, pauldendulk requested changes

2021-12-12 13:03 UTC, pauldendulk commented on Mapsui/Providers/Shapefile/Indexing/SpatialIndexing.cs
> +#pragma warning disable IDISP003
I am now halfway the MR and am now at the point where I think we should remove all the disabled IDISPXXX warnings in all our code. Even the ones that are already there. Searching in current master for 'disable IDISP' gives 40 results. And there are 71 in this MR. There can be reasons to disable a warning but we need to carefully think about that. Perhaps we should discuss them one by one. Perhaps it can indeed be ignored, but of often we should think about ownership and a possible different architecture.

This MR has many simple cases as well, for instance in the skia renderer. You create something, draw, and then you need to dispose. Those are just fine.

We should be able to work with this analyzer without having to disable all warning. Can we turn the analyzer on an off? So we could turn it on when we want to proceed with this? We do not want every MR to be full of warnings.

btw, How far do you think you have currently progresses with fixing the warnings?

2021-12-12 13:04 UTC, pauldendulk commented
Another, but related thing, I think we should add a unit these to the memory leak. This all started with a memory leak. We could add something like this https://stackoverflow.com/a/24871092/85325. A failing test is a concrete thing to guide us.

2021-12-12 13:10 UTC, inforithmics commented on Mapsui/Providers/Shapefile/Indexing/SpatialIndexing.cs
> +#pragma warning disable IDISP003
With this pull request almost all warnings are fixed. But I agree that the #pragmas hinder the readability of the Code. There are two alternatives.
1. Use an Diagnostics ignore attribute at the beginning of the method.
2. Use an Diagnostics Ignore in a Global Supressions.cs File.  
I'll think I'm going for 2. So the code stays readable.

2021-12-12 13:15 UTC, inforithmics commented on Mapsui.Core/Layers/RasterizingLayer.cs
> +        public override void Dispose()
Yes this could happen, if the Layers are cached for faster Map creation. Which is a thing I actually use. 
I solved it by Making a LayerWrapper that overrides the Dispose with a no op.

2021-12-12 13:16 UTC, inforithmics commented on Mapsui.Rendering.Skia/BitmapRenderer.cs
> +            return DefaultPaint.Clone();
I'll improve the Code here.

2021-12-12 13:17 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaWidgets/ScaleBarWidgetRenderer.cs
> +    public class ScaleBarWidgetRenderer : ISkiaWidgetRenderer, IDisposable
Good point I'll adapt it.

2021-12-12 13:18 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaWidgets/ScaleBarWidgetRenderer.cs
>                  _paintScaleBarStroke = CreateScaleBarPaint(SKPaintStyle.Stroke);
I think this is an error here.

2021-12-12 13:19 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaWidgets/ZoomInOutWidgetRenderer.cs
> +#pragma warning disable IDISP003
I'll fix it here

2021-12-12 15:47 UTC, inforithmics commented on Mapsui.Core/Styles/BitmapRegistry.cs
> +            if (_register.TryGetValue(id, out var old))
I'll change it.

2021-12-12 16:07 UTC, inforithmics commented on Mapsui.Core/Layers/RasterizingLayer.cs
> +        public override void Dispose()
I'll revert this

2021-12-12 20:56 UTC, inforithmics commented on Mapsui.Rendering.Skia/BitmapHelper.cs
> +#pragma warning disable IDISP004
I'll write a Helper funktion that creates an Picture so that only at one place this needs to be ignored. The problem is that when SKSvg gets disposed the created picture gets disposed to so here there shouldn't be a dispose.

2021-12-12 23:50 UTC, inforithmics commented
I have added memory unit Tests, that suceed nie. Maybe although bevor these changes.

2021-12-13 07:37 UTC, pauldendulk approved these changes

2021-12-13 07:37 UTC, pauldendulk commented on Tests/Mapsui.Tests/Rendering/RenderFetchStrategyTests.cs
> +                        cache.Add(tile.Index, new RasterFeature(new MRaster(Array.Empty<byte>(), new MRect(0, 0, 1, 1))));
Oh!  I think I should have mentioned this before, but MemoryStream does **not** need to be disposed. It has a IDispose interface because this is a generic interface for all streams but the MemoryStream is an exception and does not need to be disposed. Perhaps there should be a comment in code about this. And with respect to performance we want to limit the number of times the bitmaps bytes need to be copied. I think I want to revert this, I am not sure if this causes an extra copy, perhaps not, because BruTile works with byte arrays.

2021-12-13 07:37 UTC, pauldendulk commented on Tests/Mapsui.Tests/Fetcher/FetchMachineTests.cs
> +            return new RasterFeature(new MRaster(tile, tileInfo.Extent.ToMRect()));
ah, there was already a copy in the original code. So, let's just keep MRaster Data as byte array.

2021-12-13 07:37 UTC, merged

2021-12-13 07:40 UTC, pauldendulk commented
After merging this master has 33 results when searching on 'disable IDISP'.

2021-12-13 07:54 UTC, pauldendulk commented
I created a little research project and what is interesting is that this test fails:

https://github.com/pauldendulk/ResearchDispose/commit/4ef6682acf75a387130dad83e984f7f9b03edf26#diff-7a20f319ad5744f87d00ab1ec1efc602f060545b25112d2513e9c55ac7f81856R26

The test above, which seems to be equivalent, succeeds. The Map that is created here is a completely empty class with no IDispose interface. I assume the GC does not collect it because the Target field is access in the local function.

2021-12-13 21:31 UTC, inforithmics commented
Maybe the Static Methodd need to bee decorated with a noinling Attribute.
Because with inlining the Target comes again into method scope and it ist
not Garage collected.

Paul den Dulk ***@***.***> schrieb am Mo., 13. Dez. 2021,
8:54 AM:

> I created a little research project and what is interesting is that this
> test fails:
>
> ***@***.***
> #diff-7a20f319ad5744f87d00ab1ec1efc602f060545b25112d2513e9c55ac7f81856R26
> <https://github.com/pauldendulk/ResearchDispose/commit/4ef6682acf75a387130dad83e984f7f9b03edf26#diff-7a20f319ad5744f87d00ab1ec1efc602f060545b25112d2513e9c55ac7f81856R26>
>
> The test above, which seems to be equivalent, succeeds. The Map that is
> created here is a completely empty class with no IDispose interface. I
> assume the GC does not collect it because the Target field is access in the
> local function.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mapsui/Mapsui/pull/1420#issuecomment-992197319>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARPJLZQ747M76SZ2JIVXHTUQWRCVANCNFSM5J3NWM3Q>
> .
>

2021-12-14 07:43 UTC, pauldendulk commented
Well, by putting it in a separate method it is solved as well. It is okay like this. It was a surprise to me though, that is why I mentioned it, but later I saw in your code comments you had discovered the same problem and had the same solution, so I deleted my remark.