Fixed Callout Pin Rotation
Mapsui/Mapsui pull request #1504
Opened 2022-02-17 23:21 UTC by inforithmics

Fixing this https://github.com/Mapsui/Mapsui/issues/1503

2022-02-17 23:26 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
This change is semantically the same as the original Code, But makes a big difference on screen.  This is the original Code piece and this works. Maybe @charlenni has more insight here.  For me it seems a Numeric-Compiler-Precision Problem.

2022-02-17 23:26 UTC, inforithmics commented on Mapsui.Rendering.Skia/PictureRenderer.cs
> -            var matrix = SKMatrix.CreateTranslation(rect.Left, rect.Top);
This is a Bug I discovered in my TilingRasterizing Pull request the Picture didn't scale properly.

2022-02-17 23:50 UTC, inforithmics commented
When 
https://github.com/Mapsui/Mapsui/pull/1502

goes in this should become green

2022-02-18 06:45 UTC, pauldendulk reviewed
I would like to be able to reproduce this problem so I can understand how it is fixed.

2022-02-18 06:45 UTC, pauldendulk commented on Mapsui.Rendering.Skia/PictureRenderer.cs
> -            var matrix = SKMatrix.CreateTranslation(rect.Left, rect.Top);
This seems a serious bug. Good to fix it right away, but for my understanding, this is not This is not a cause of the rotation original problem, right?

2022-02-18 06:45 UTC, pauldendulk commented on Mapsui.Rendering.Skia/PictureRenderer.cs
> +            matrix = matrix.PostConcat(SKMatrix.CreateScale(scaleX, scaleY));
This too. Basically this code had no effect before this fix. Where in the samples can I see it's effect?

2022-02-18 06:45 UTC, pauldendulk commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
This is very strange. Everything I know says it should be the same. I introduced this bug and I would introduce it again if I saw this code later. I am not a big fan of code comments, because they get outdated easily (better to use a more readable code style) but this a situation where code comments are really needed.

2022-02-18 07:17 UTC, inforithmics commented
I'll add an Code Comment.

2022-02-18 07:43 UTC, inforithmics commented on Mapsui.Rendering.Skia/PictureRenderer.cs
> +            matrix = matrix.PostConcat(SKMatrix.CreateScale(scaleX, scaleY));
I found this Bug in my Tile Rendering Pull request when I Rendered SkPictures. I'll look if there are Pictures scaled in mapsui. If they are then I will make a separate pull request

2022-02-18 08:37 UTC, janusw commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
I can confirm that this PR fixes the problem. Pretty strange that this change would make any difference ...

2022-02-18 09:00 UTC, janusw requested changes
The CalloutStyleRenderer part is certainly ok with me (ideally with a comment).

The PictureRenderer part should probably stay out of this, or go into a separate commit at least, since it seems to be completely unrelated.

Thanks for taking care of this so quickly!

2022-02-18 09:02 UTC, janusw commented
> When #1502
> 
> goes in this should become green

It is in master, so this PR should be rebased to master ...

2022-02-18 10:21 UTC, charlenni commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
Looking into it, it is totally clear, that this lines are totally different (had to think about it some time, but sounds better, to say it is totally clear  ;-) ).

The existing is 

    a = a - b
    b = a + b

The first line changes `a`, so that it isn't the same as before, when you go to the second line. It is like you do a swap with

    a = b
    b = a

In our case, `symbolOffsetX` is replaced by a new value, but used in the next line as if it has the old value.

I hope, now it is clear, what the problem was.

2022-02-18 11:32 UTC, janusw commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
Ah, sure 🙈. Totally missed that. So it's not about numeric conversion at all, but there is indeed a good reason for the temporary variables!

2022-02-18 11:38 UTC, janusw commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
So maybe it would be a good idea to clean this up a little: Represent the offset as an `MPoint` and use `MPoint.Rotate` for the rotation?

2022-02-18 16:13 UTC, janusw commented on Mapsui.Rendering.Skia/SkiaStyles/CalloutStyleRenderer.cs
> +                symbolOffsetY = (float)y1;
I'm trying this in #1508, which is an alternative to this PR. Any feedback?

2022-02-18 17:01 UTC, closed without merging