(WIP) Use DotSpatial.Projection for Projection Improvements
Mapsui/Mapsui pull request #1528
Opened 2022-02-28 12:56 UTC by inforithmics

2022-03-06 08:42 UTC, pauldendulk reviewed
Thanks a lot for the MR. Better projection support has been on the wish list for a long time. I need to think about the extra dependency though.

2022-03-06 08:42 UTC, pauldendulk commented on Mapsui/Providers/ProjectingProvider.cs
> +            _projection = projection ?? ProjectionDefaults.Projection;
We should try to reduce our use of static fields. Usually things like this would be solved with dependency injection. Perhaps we should start using some form of dependency injection. This nuget is what I use in my backend projects [Microsoft.Extensions.DependencyInjection.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions) but I am not sure how that interoperates with what is used in MAUI (could use exactly the same) and for instance Avalonia (could use something different).

It could help with a lot of our other design issues as well.

2022-03-06 08:42 UTC, pauldendulk commented on Tests/Mapsui.Tests/Mapsui.Tests.csproj
> +		<ProjectReference Include="..\..\Samples\Mapsui.Samples.Common.Desktop\Mapsui.Samples.Common.Desktop.csproj" />
Why is Mapsui.Samples.Common.Desktop added? 

We should go the other way. Spit it up more. Mapsui.Tests should only have a dependency on Mapsui and nothing else (exception external dependencies that help with testing). The fact that it is not at the moment is a consequence of my refactoring, which is basically not finished yet. There should be a Mapsui.Tiling.Tests with a dependency on Mapsui.Tiling and there should be a Mapsui.Nts.Tests with a dependency on Mapsui.Nts. Mapsui.Rendering.Skia already has a test project.

2022-03-06 08:42 UTC, pauldendulk commented on Mapsui.Nts/Mapsui.Nts.csproj
>    <ItemGroup>
The Mapsui.Nts.dll is in the core Mapsui nuget so now it will also have a dependency on DotSpatial.Projects. I would like to avoid that but not sure how.

2022-03-06 13:23 UTC, inforithmics commented
A possibility would be to make mapsui extensions nuget package/project and but the dependency and code there. So if someone doesn't need this functionality the dependency wouldn't be added.

2022-03-15 18:55 UTC, pauldendulk requested changes
Looks great! Just a few comments you could look at.

2022-03-15 18:55 UTC, pauldendulk commented on Tests/Mapsui.Tests/Projections/ProjectionTests.cs
> +        public void CoordinateNtsProjectionTest()
Thanks for adding unit tests!

2022-03-15 18:55 UTC, pauldendulk commented on Tests/Mapsui.Tests/Projections/ProjectionTests.cs
> +            DotSpatialProjection.Init();
I could not really guess what was happening in the Init method. Perhaps it is better not to have an Init method and just use the code like this:

        ProjectionDefaults.Projection = new DotSpatialProjection();
        ProjectionDefaults.CrsFromEsri = CrsFromEsri;

And Perhaps CrsFromEsri should just be set in ProjectionDefaults itself. There is no other option right now, so why not.

2022-03-15 18:55 UTC, pauldendulk commented on Mapsui.Extensions/Projections/DotSpatialProjection.cs
> +    public static string CrsFromEsri(string esriString)
Perhaps this method should be in it's own class. It is not tied to the projection. It is related to projections but not itself a projection and CrsFromEsri could be used in combination with another projection.

2022-03-15 18:55 UTC, pauldendulk commented on Mapsui.Extensions/Mapsui.Extensions.csproj
> +    <!--<PackageReference Include="DotSpatial.Projections" Version="3.0.0" IncludeAssets="None" ExcludeAssets="All" PrivateAssets="None" GeneratePathProperty="true" NoWarn="NU1202;NU1701" />-->
Can these commented out parts be removed.

2022-03-15 19:58 UTC, pauldendulk commented on Tests/Mapsui.Tests/Projections/ProjectionTests.cs
> +            DotSpatialProjection.Init();
And if the CrsFromEsri is set globally perhaps you need only the first line.

2022-03-24 12:59 UTC, inforithmics commented on Mapsui/Providers/ProjectingProvider.cs
> +            _projection = projection ?? ProjectionDefaults.Projection;
I reverted this change, dependencies should come with the constructor so they are not dependent on any Dependency Injection framework. Because Mapsui is a component it should not dependend on a specific one. But dependencies should be specified by constructor.

2022-03-24 13:03 UTC, inforithmics commented on Tests/Mapsui.Tests/Mapsui.Tests.csproj
> +		<ProjectReference Include="..\..\Samples\Mapsui.Samples.Common.Desktop\Mapsui.Samples.Common.Desktop.csproj" />
removed now. I tried something and then I forgot to remove it afterwards.

2022-03-24 13:04 UTC, inforithmics commented on Tests/Mapsui.Tests/Projections/ProjectionTests.cs
> +            DotSpatialProjection.Init();
Is no removed and a Parameter in the Constructor.

2022-03-24 13:05 UTC, inforithmics commented on Mapsui.Extensions/Mapsui.Extensions.csproj
> +    <!--<PackageReference Include="DotSpatial.Projections" Version="3.0.0" IncludeAssets="None" ExcludeAssets="All" PrivateAssets="None" GeneratePathProperty="true" NoWarn="NU1202;NU1701" />-->
cleaned up

2022-03-27 07:32 UTC, pauldendulk commented on Mapsui/Providers/ProjectingProvider.cs
> +            _projection = projection ?? ProjectionDefaults.Projection;
I have been looking in MAUI a bit more and they are indeed using Microsoft.Extensions.DependencyInjection.Abstractions. Perhaps we can add helper methods to register Mapsui core services.

2022-03-27 07:56 UTC, pauldendulk approved these changes
Thanks for picking up the comments. This going back and forth is making things better. One more remark you could look at.

2022-03-27 07:56 UTC, pauldendulk commented on Mapsui.Extensions/Projections/DotSpatialProjection.cs
> +    public int? GetIdFromCrs(string? crs)
Looks like this method can be private now.

2022-03-27 07:56 UTC, merged