Map renderer add image format
Mapsui/Mapsui pull request #1706
Opened 2022-09-04 20:00 UTC by inforithmics

Specify the RenderFormat in the IMapRenderer Interface

2022-09-18 20:29 UTC, inforithmics commented
General idea behind this pull request. 

The MapRenderer can now render to differnt Formats.
1. png (as before)
2. webp (better compression as png) (losless)
3. skp (Skia Vector format with that you get the speed of a bitmap renderer with the sharpness of skia vector graphics with caching of the vectors in persitant format if desired).
4. Currently it works but sometimes a memory exception occours (maybe a dispose on a skpicture where it shouldn't be I'm investigating this). When I have fixed this this pull request can be reviewed. Maybe it solves this (https://github.com/Mapsui/Mapsui/issues/1711)

2022-09-18 23:20 UTC, charlenni commented
The SKPicture isn't as fast as a bitmap. It only records only all draw commands and replays them, if it is drawn. So you save the conversions from Mapsui features to drawing commands. But the drawing itself saves no time.

2022-09-21 09:17 UTC, inforithmics commented
Good point, I'll make a Benchmark.net Test where I compare the Performance of the different Rendering formats. I Currently I have a Bug in the Test and therefore the numbers are not correct yet.

2022-10-01 14:51 UTC, inforithmics commented
|                      Method |     Mean | Error |      Min |      Max |   Median |
|---------------------------- |---------:|------:|---------:|---------:|---------:|
|     RenderRasterizingTiling | 30.48 ms |    NA | 30.48 ms | 30.48 ms | 30.48 ms |
|  RenderRasterizingTilingPng | 16.47 ms |    NA | 16.47 ms | 16.47 ms | 16.47 ms |
| RenderRasterizingTilingWebP | 17.57 ms |    NA | 17.57 ms | 17.57 ms | 17.57 ms |
|  RenderRasterizingTilingSkp | 17.26 ms |    NA | 17.26 ms | 17.26 ms | 17.26 ms |

2022-10-01 16:07 UTC, inforithmics commented
I think I have fixed all the bugs I know off and the Performance is acceptable too. So with skp you get almost the Performance of png and the sharpness of the default renderer

2022-10-06 14:29 UTC, pauldendulk requested changes
Benchmark dotnet was added. This is awesome! I have some things I would like to discuss. Not big things, but it is just not handy to do this is all in text, we should have a zoom call. In general, I think it is necessary to have these from time to time.

2022-10-06 14:29 UTC, pauldendulk commented on Mapsui.Rendering.Skia/MapRenderer.cs
> +                MemoryStream? memoryStream;
This method is not easy for me to understand. There is an if and two swiches on renderformat within a fairly long method. A 'surface' variable is declared but it is used only in some of the flows. Instead of trying to understand it I would prefer to invest time in making it more readable, so others and future-me could also understand it. Let's look into this together. I can have a zoom call on next Monday, Thursday or Wednesday. I will contact you in our developers chat.

2022-10-06 14:29 UTC, pauldendulk commented on Mapsui/Rendering/IRenderer.cs
> +            Color? background = null, float pixelDensity = 1, IEnumerable<IWidget>? widgets = null, ERenderFormat renderFormat = ERenderFormat.Png);
Makes sense to add several options.

2022-10-06 15:14 UTC, inforithmics commented on Mapsui/Rendering/ERenderFormat.cs
> +    public enum ERenderFormat
E equals RenderFormat

2022-10-06 17:48 UTC, inforithmics commented on Directory.Packages.props
> +    <!--<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>-->
So when Maui updates it's dependencies, the referenced dependencies are taken and I don't have to fix all dependencies in the Central.Packages

2022-10-06 17:48 UTC, inforithmics commented on Directory.Packages.props
> +    <!--<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>-->
One example is Windows.App.Sdk

2022-10-06 17:49 UTC, inforithmics commented on Directory.Packages.props
> +    <!--<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>-->
The same is true for the Uno Dependencies which are worse then the Maui dependencies

2022-10-06 17:52 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/PictureRenderer.cs
> +            var matrix = SKMatrix.CreateScaleTranslation(scaleX, scaleY, rect.Left, rect.Top);
At the end of the Zoom they where correct but the zooming animation didn't work.

2022-10-06 17:58 UTC, inforithmics commented on Mapsui/Extensions/StreamExtensions.cs
> +        public static bool IsSkp(this byte[] buffer)
Fixed

2022-10-09 17:10 UTC, inforithmics commented
I remeasured (The RenderToBitmap method took the most time for saving to a png file)

|                           Method |     Mean |     Error |    StdDev |      Min |       Max |   Median |
|--------------------------------- |---------:|----------:|----------:|---------:|----------:|---------:|
|               RenderDefaultAsync | 9.445 ms | 0.1885 ms | 0.4587 ms | 8.684 ms | 10.395 ms | 9.364 ms |
|  RenderRasterizingTilingPngAsync | 3.978 ms | 0.0794 ms | 0.2007 ms | 3.616 ms |  4.480 ms | 3.979 ms |
| RenderRasterizingTilingWebPAsync | 3.883 ms | 0.0771 ms | 0.0918 ms | 3.727 ms |  4.047 ms | 3.906 ms |
|  RenderRasterizingTilingSkpAsync | 6.924 ms | 0.1375 ms | 0.2869 ms | 6.389 ms |  7.549 ms | 6.949 ms |

2022-10-11 10:49 UTC, IldarKhayrutdinov commented on Mapsui/Extensions/ByteArrayExtensions.cs
> +    /// <summary> true if is Xml </summary>
typo

2022-10-11 19:45 UTC, inforithmics commented on Mapsui/Extensions/ByteArrayExtensions.cs
> +    /// <summary> true if is Xml </summary>
Thanks for finding this, will fix it

2022-10-11 19:49 UTC, inforithmics commented
I added automatic compression to SqlitePersistentCache, when the data is compressible it is saved with Brotli. This reduces the Skp Cache Size for example from 120kb to roughly 60kb.

2022-10-11 22:43 UTC, inforithmics commented
I added The The located Memory to a Benchmark.Net run: Here one can see that the Rasterizing is mainly faster because a lot less memory is allocated 2MB vs 11KB.

|                           Method |     Mean |     Error |    StdDev |      Min |      Max |   Median |     Gen0 |  Allocated |
|--------------------------------- |---------:|----------:|----------:|---------:|---------:|---------:|---------:|-----------:|
|               RenderDefaultAsync | 8.213 ms | 0.0976 ms | 0.0865 ms | 8.099 ms | 8.380 ms | 8.204 ms | 265.6250 | 2720.19 KB |
|  RenderRasterizingTilingPngAsync | 3.797 ms | 0.0732 ms | 0.0900 ms | 3.723 ms | 4.026 ms | 3.757 ms |        - |   11.72 KB |
| RenderRasterizingTilingWebPAsync | 3.700 ms | 0.0346 ms | 0.0307 ms | 3.657 ms | 3.774 ms | 3.702 ms |        - |   11.72 KB |
|  RenderRasterizingTilingSkpAsync | 6.226 ms | 0.0985 ms | 0.0921 ms | 6.138 ms | 6.401 ms | 6.191 ms |        - |   11.92 KB |

2022-10-15 10:39 UTC, pauldendulk approved these changes

2022-10-15 10:39 UTC, merged