First attempt for a MapBuilder
Mapsui/Mapsui pull request #2346
Opened 2023-12-15 09:13 UTC by charlenni

This is the first attempt of a MapBuilder implementation. I'm not sure, if it is good and useful. For me, it is only a replacement for a good documentation.

2023-12-16 19:12 UTC, pauldendulk requested changes
Thanks, this makes it more concrete, still lot of questions pop up. 

The most important thing still missing is a method that builds a more complex commonly used configuration. So, a one line method could add the osm layer, assign the CRS, add a scalebar, zoom buttons, add the navigation layer, things like that. Not sure how it should be called, AddNavigationProfile() or SetupNavigationApp() or AddNavigationConfiguration(), ConfigureForNavigation().

Perhaps we should just merge this as experimental and play with it. We are not even in beta so could remove it again. 

There are a few small things in the remarks that you could change.

2023-12-17 13:41 UTC, charlenni commented
It was meant as a first version. So I didn't add very complicated things. I first want to have comments on this.

I will work a little more on this before we could add it.

2023-12-17 13:44 UTC, charlenni commented on Mapsui/MapBuilder.cs
> +    readonly Map _map = new Map { CRS = "EPSG:3857" };
We could save the adds in lists for layers and widgets. The rest must kept in extra values.

But all this is redundant. So why not create a Map at the beginning and save all this into this Map.

2023-12-17 13:47 UTC, charlenni commented on Mapsui/MapBuilder.cs
> +    public Map Map => _map;
Yes, but how to add then e.g. the OSM layer? It is created in Mapsui.Tiling. So it makes changes to Map, but MapBuilder don't know anything about this layer.

If you want to have such a behavior, then we should use a AddLayer(ILayer) in MapBuilder. Is this, what you like?

2023-12-17 13:48 UTC, charlenni commented on Mapsui/MapBuilder.cs
> +    public static MapBuilder Create()
You are right

2023-12-17 13:49 UTC, charlenni commented on Mapsui/Extensions/MapBuilderExtensions.cs
> +        var zoomInSvg = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\"><g stroke=\"#000\"><circle cx=\"20\" cy=\"20\" fill=\"#fff\" stroke-width=\"2\" r=\"18\"/><path d=\"M10 2
Yes, but it seems good enough for this example 😉

2023-12-17 13:53 UTC, charlenni commented on Mapsui/Extensions/MapBuilderExtensions.cs
> +        var scalebar = new ScaleBarWidget(mapBuilder.Map)
That is the reason why I said, that I'm not sure, if we need such a thing. But let's see, if we have a benefit at the end. If not, then we could drop this PR.

2023-12-17 13:53 UTC, charlenni commented on Mapsui.Tiling/Extensions/MapBuilderExtensions.cs
> +    public static MapBuilder AddOsmMap(this MapBuilder mapBuilder, string? userAgent = null)
Correct. AddOsmLayer() is much better.

2023-12-17 16:18 UTC, charlenni commented on Mapsui/MapBuilder.cs
> +    readonly Map _map = new Map { CRS = "EPSG:3857" };
I now changed the code in the way, that Map is created in the Build() function. But then how to add widgets like ScaleBar, which need the Map in the constructor? Any ideas for this?

2023-12-17 16:19 UTC, charlenni commented on Mapsui/MapBuilder.cs
> +    public Map Map => _map;
I could do this by adding Layers and Widgets to an internal list of ILayer and IWidget and create the Map in Build(). But then I could never create widgets like ScaleBar, which need a Map when creating.

2023-12-18 07:27 UTC, pauldendulk commented on Mapsui/MapBuilder.cs
> +    public Map Map => _map;
I did not consider that Map was needed in the constructor of some of the widgets.

I could add that it is better if the widgets would not depend on the Map class because now they have a circular dependency, which in general you want to avoid, but that is another topic. 

A possible solution would be to work with Configure methods on the Builder like in the code below. But you would need to store the actions too. Possible, but it all becomes a bit fancy.

```csharp
public class Program
{
    static void Main()
    {
        var builder = new Builder();
        builder.AddWidget();
        var map = builder.Build();
        Console.WriteLine($"Number of widgets: {map.Widgets.Count()}");
    }
}

public class Map()
{
    public List<Widget> Widgets { get; } = [];

    internal void Widget(Widget widget)
      => Widgets.Add(widget);
}

public record class Widget(Map Map);

public class Builder
{
    readonly List<Action<Map>> _actions = [];

    public Map Build()
    {
        var map = new Map();
        foreach (var action in _actions)
            action(map);
        return map;
    }

    public void Configure(Action<Map> builder)
      => _actions.Add(builder);
}

public static class BuilderExtensions
{
    public static Builder AddWidget(this Builder builder)
    {
        builder.Configure(map => map.Widget(new Widget(map)));
        return builder;
    }
}
```

2023-12-18 08:07 UTC, pauldendulk commented
Let's not add the MapBuilder.

The general feeling I get is that we are adding a layer around the Map and we would need to add more methods over time to be able to call functionality that is available on the Map.

Perhaps an alternative is to use extension methods on the Map to make it easy to add a specific configuration.

It is unfortunate to build something and then to discard it, but I think this is how we should work. Thanks for helping to think critically about this proposal.

For me the most important use cases were:
- Enforce that that the logging widget is added. I now intend to add the in the Map itself. Which is against the idea that we should have simple Lego like components which we combine in a later step.
- Make it easy to add a complex configuration to the MapControl that is similar to what is in the MapView. Perhaps this can be done with an extension method.

2023-12-18 09:29 UTC, charlenni commented
Good decision. And no problem for me.

I will come back with another PR for the extension method approach, and then we could discuss this.

2023-12-18 10:05 UTC, closed without merging