WIP Aot
Mapsui/Mapsui pull request #2349
Opened 2023-12-16 09:53 UTC by inforithmics

2023-12-16 09:55 UTC, inforithmics commented
Currently it is failing because of Reflection getting the Samples. I think I will write a Source Generator for that, than this becomes AOT Compatible.

2023-12-16 12:00 UTC, pauldendulk commented
I don't know how much work it would be, and more importantly how maintainable the source generators will be, but perhaps we do not need the the samples to be AOT. Or perhaps just one sample demonstrating that it works. ... Then again it would be nice if our own online samples are AOT, to see if it is actually faster.

2023-12-16 12:49 UTC, inforithmics commented
> I don't know how much work it would be, and more importantly how maintainable the source generators will be, but perhaps we do not need the the samples to be AOT. Or perhaps just one sample demonstrating that it works. ... Then again it would be nice if our own online samples are AOT, to see if it is actually faster.

I do a lot of Mobile Development and there because of AOT and Performance issues I try to avoid Reflection, The solution is Source Generators, which do the Refelection during compilation time. Making the App faster and AOT safe.

2023-12-16 14:31 UTC, pauldendulk commented
Okay, lets go ahead with code generation.

2023-12-17 13:30 UTC, inforithmics commented
Things done: 
1) Samples are now Registered with SourceCodeGenerator. Avoiding Reflection speeds up the inital Sample Display quite a lot
2) Blazor is Compiled with publish AOT and Strip Symbols for faster startup and loading

2023-12-17 17:20 UTC, inforithmics commented
There are still 2 AOT Warnings, but in my opinion they shouldn't matter, or I don't know how to fix them.

2023-12-19 21:42 UTC, inforithmics commented
Additional Things done:
1) Delete Mapsui.Mac.Legacy.sln (isn't needed anymore because there is no Xamarin.Forms)
2) Fixed current Dispose Warnings

2023-12-29 16:18 UTC, pauldendulk reviewed
Great you took this up! Quite a lot to learn. I suspected this would be something for you.

You have a [WIP PR](https://github.com/BruTile/BruTile/pull/225) at BruTile. So, this needs to be reviewed, merged, released and updated in Mapsui before it can be used. What will not work as long is that is not the case? 

This is a new technology so a have some questions about the changes to help me understand. Please take a look.

Also, I need to read up on source generator. Any recommendations?

2023-12-29 16:18 UTC, pauldendulk commented on Mapsui.UI.Shared/MapControl.cs
> +                _ownsMap = true;
Complicated 🤨

2023-12-29 16:18 UTC, pauldendulk commented on Mapsui/Extensions/FeatureExtensions.cs
> +        if (feature is PointFeature pointFeature)
So what if a user adds a custom renderer and uses a custom feature type?

2023-12-29 16:18 UTC, pauldendulk commented on Mapsui/Fetcher/FetchWorker.cs
> +#if NET8_0_OR_GREATER
I never like the #ifs. Perhaps we can make them less ugly if we create a CancelAsync extension method for 6. That method should still have a #if !NET8_0_OR_GREATER, but at least it will be in one place, and in code you do not read that often.

2023-12-29 16:18 UTC, pauldendulk commented on Samples/Avalonia/Mapsui.Samples.Avalonia/Views/MainView.axaml.cs
> +        Mapsui.Tests.Common.Samples.Register();
Thats an easy fix.

2023-12-30 11:51 UTC, pauldendulk commented
@inforithmics I resolved a conflict in the browser, you may want to check it https://github.com/Mapsui/Mapsui/pull/2349/commits/ddc9e2969625ff339786ecb67ddff0a6bed38997

2024-01-05 06:07 UTC, inforithmics commented on Directory.Build.props
> +<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
According to this
https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/
IsAotCompatible is available on .NET 7 Framework and later, that's why it is definied this way. So this needs addtional Targets for mapsui. This is the reason why I added the .NET 7 and .NET 8 Targets to Mapsui Projects

2024-01-05 06:08 UTC, inforithmics commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="[8.0.0,9.0.0)" />
good point will remove it

2024-01-05 06:10 UTC, inforithmics commented on Mapsui.ArcGIS/Mapsui.ArcGIS.csproj
> +    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
Yes that's right, if something doesn't compile with .NET 6 it will get a compilation error. Or can be conditional compiled.
with 
```
#if NET6_0
#else
#endif
```
or
```
#if NET7_0_OR_GREATER
#else
#endif
```

2024-01-05 06:13 UTC, inforithmics commented on Mapsui.Nts/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Trimming", "IL2111:Method with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of th
The IL messages are warnings and not errors that's why they can be surpressed, and sometimes the Analyzer has a Bug so it warns on something that works. Because in my opinion here is no reflection involved here (the Interface was to broadly tagged as DynamicCode).

2024-01-05 06:16 UTC, inforithmics commented on Mapsui.UI.Maui/MapControl.cs
> +    private bool _ownsMap;
I think with the removal of the Skia Objects, the Map can be made again non disposable. I think I will revert this here and make a seperate pull request for that.
The reason I did this was to fix the warnings but It seems not to be a quick fix.

2024-01-05 06:19 UTC, inforithmics commented on Directory.Packages.props
> +    <PackageVersion Include="System.Text.Json" Version="[8.0.0,9.0.0)" />
I have to look if I can remove this

2024-01-05 06:26 UTC, inforithmics commented
> Great you took this up! Quite a lot to learn. I suspected this would be something for you.
> 
> You have a [WIP PR](https://github.com/BruTile/BruTile/pull/225) at BruTile. So, this needs to be reviewed, merged, released and updated in Mapsui before it can be used. What will not work as long is that is not the case?

AOT has some Basic support for reflection, so when there is a warning about not beeing AOT compatible it might work or not. So this has to be tested on the resulting Program and cannot be done on the Library level. Making an assembly AOT compatible means removing all scenarios that involve reflection and certain Code patterns so that it always works.

I already use AOT on Mobile Applications with mapsui this means I have had to annotate Code as beeing used so that it wasn't removed.

In the Case of Brutile I think the WMTS Support uses XmlSerializer that uses reflection. So this could be working or not. If the AOT compiler is to aggressive and removes Things that are needed for the XmlSerializer than WMTS wouldn't work in an AOT scenario.

> 
> This is a new technology so a have some questions about the changes to help me understand. Please take a look.
> 
> Also, I need to read up on source generator. Any recommendations?

Is a good introduction
https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

2024-01-05 06:32 UTC, inforithmics commented on Mapsui/Fetcher/FetchWorker.cs
> +#if NET8_0_OR_GREATER
I'll try that

2024-01-05 06:33 UTC, inforithmics commented on Mapsui/Extensions/FeatureExtensions.cs
> +        if (feature is PointFeature pointFeature)
I could add as fall back the old Activator.CreateInstance method.

2024-01-05 06:38 UTC, inforithmics commented on Mapsui/Extensions/FeatureExtensions.cs
> +        if (feature is PointFeature pointFeature)
Or I could add a source generator to Mapsui that does this autmatically.

2024-01-05 06:41 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +                _ownsMap = true;
Maybe I could introduce a DisposableWrapper that is always disposed but has a member with the value ownsDisposable and when it is true then it disposes the disposable else it sets only the member to null.
So the reading the code is more straight forward.

2024-01-06 16:57 UTC, inforithmics commented
Things done: Clean up nuget packages and removed appveyer.testloggger (isn't used anymore)

2024-01-06 17:05 UTC, inforithmics commented on Mapsui/Fetcher/FetchWorker.cs
> +#if NET8_0_OR_GREATER
Done

2024-01-06 17:32 UTC, inforithmics commented on Directory.Packages.props
> +    <PackageVersion Include="System.Text.Json" Version="[8.0.0,9.0.0)" />
I did remove all unneded nuget packages from Directory.Packages.props so simplifiying it quite a bit.

2024-01-06 17:33 UTC, inforithmics commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="[8.0.0,9.0.0)" />
Done

2024-01-06 17:34 UTC, inforithmics commented on Mapsui.UI.Maui/MapControl.cs
> +    private bool _ownsMap;
The Dispose in the map is used to stop the Fetching of Data and Deregister EventHandlers

2024-01-06 17:34 UTC, inforithmics commented on Mapsui/Extensions/FeatureExtensions.cs
> +        if (feature is PointFeature pointFeature)
I'll try adding a SourceGenerator

2024-01-07 11:31 UTC, pauldendulk commented on Mapsui.ArcGIS/Mapsui.ArcGIS.csproj
> +    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
I would like to avoid #if's as much as possible.

2024-01-07 11:33 UTC, pauldendulk commented on Mapsui.UI.Shared/MapControl.cs
> +                _ownsMap = true;
Let keep it like this and start thinking about making the Map not-disposable.

2024-01-07 11:34 UTC, pauldendulk commented on Mapsui/Extensions/FeatureExtensions.cs
> +        if (feature is PointFeature pointFeature)
Did you manage to fix this with a source generator?

2024-01-07 11:36 UTC, inforithmics commented on Mapsui/Extensions/FeatureExtensions.cs
> +        if (feature is PointFeature pointFeature)
Yes, in Mapsui the SourceGenerator Project is referenced and in the mapsui nuget package a compiled version of the SourceGenerator is included, executing it during the build on librarie that reference the mpasui nuget package.

2024-01-07 11:41 UTC, pauldendulk commented on Mapsui.Rendering.Skia/GlobalSuppressions.cs
> +[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Rendering.Skia.MapRe
We really need to come up with a  redesign where these suppressions are not needed.

2024-01-07 12:31 UTC, inforithmics commented on Mapsui.Rendering.Skia/GlobalSuppressions.cs
> +[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Rendering.Skia.MapRe
Analyzers are sometimes not 100 % accurate and give sometimes more hints. So to avoid pulluting the Source Code a add the regressions to GlobalSuppressions.cs so that the reading flow of the source code isn't hindered.
Maybe an update to the Anlyzer improves things.

2024-01-07 17:08 UTC, inforithmics commented
Brutile IsAatCompatible is now available
https://github.com/BruTile/BruTile/pull/225

2024-01-12 08:53 UTC, pauldendulk commented on Mapsui.Rendering.Skia/GlobalSuppressions.cs
> +[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP003:Dispose previous before re-assigning", Justification = "<Pending>", Scope = "member", Target = "~M:Mapsui.Rendering.Skia.MapRe
In case of the ownership issue the code may be correct, but if the analyzer gets confused about who is owning the disposable then it is also confusing for us. So, in case of the ownership of the Map I would think the analyzer is correct and we should choose to either make the MapControl own or the user. It is simpler, even if the current code is correct. (This is just an example, in case of the Map control we should look into making it non-disposable).

2024-01-12 09:15 UTC, pauldendulk reviewed
I added a few more comments and have two additional things I would like you to look at. 
- Could a if (RunningInAotMode) exception be added?
- Do we really need the namespace in UI.Maui.MapView? I have been removing such namespaces in the cleanup in previous weeks and would like to have a 'Only add namespace in code if really needed' policy.

2024-01-12 09:15 UTC, pauldendulk commented on Mapsui/Extensions/FeatureExtensions.cs
> +        return (IFeature)Activator.CreateInstance(type, feature)!;
This is an improvement compared to the earlier version but my understanding is that custom features will not work in AOT. I don't think this is a problem, but it is important that the user gets a clear error message in that case.  So underneath the '// Fall Back ...'  line there should be a check:

```csharp
if (RunningInAotMode) 
   throw new NotSupportedException("Custom feature types are not supported when running in AOT"). 
```

2024-01-12 09:15 UTC, pauldendulk commented on Samples/Mapsui.Samples.MapView/AnimatedMyLocationSample.cs
> +    private UI.Maui.MapView? _mapView;
These namespace changes seem unrelated to AOT, why is the now necessary?

2024-01-12 09:15 UTC, pauldendulk commented on Directory.Packages.props
> -    <PackageVersion Include="Xam.Plugin.Geolocator" Version="[5.0.0-beta,6.0.0)" />
Great you removed all the package not in use. This was an item on the roadmap https://mapsui.com/documentation/roadmap.html#mapsui-5

2024-01-12 09:15 UTC, pauldendulk commented on Mapsui.UI.Shared/MapControl.cs
> +                _map ??= new DisposableWrapper<Map>(new Map(), true);
I guess this is an improvement. I will have to look at this a bit better later one. As discussed elsewhere, a better solution would be to make the Map non-disposable.

2024-01-12 09:15 UTC, pauldendulk commented on Mapsui.sln
> +		{AE094043-B696-49D4-8F58-2523047A6210}.Ad-Hoc|AnyCPU.ActiveCfg = Debug|Any CPU
What a horrible bloat of sln entries. Added by by VS I guess, but perhaps based on the configurations we have defined elsewhere in the project. I don't expect this bloat if we would create a new project from scratch. This is not something to fix in this PR, and perhaps this should have no priority at all, but if anyone knows the way to simplifies this I would be interested.

2024-01-22 07:42 UTC, pauldendulk commented on Mapsui.sln
> +		{AE094043-B696-49D4-8F58-2523047A6210}.Ad-Hoc|AnyCPU.ActiveCfg = Debug|Any CPU
It would be nice if we could reduce the configuration bloat one day. But not today 😟

2024-01-22 07:50 UTC, pauldendulk commented on Mapsui/Extensions/FeatureExtensions.cs
> +        return (IFeature)Activator.CreateInstance(type, feature)!;
@inforithmics I think it is important to have an exception here. If not this could be very frustrating for users. Could you look into this?

2024-01-22 07:50 UTC, pauldendulk requested changes
I have one question left, and one remark about adding an exception. If fixed I will merge this asap.

2024-01-22 11:16 UTC, pauldendulk commented
@inforithmics I caused a conflict, tried to solve it in the browser but I am not quite sure about how, so please take a look yourself.

2024-01-22 22:35 UTC, inforithmics commented on Samples/Mapsui.Samples.MapView/AnimatedMyLocationSample.cs
> +    private UI.Maui.MapView? _mapView;
The reason this is needed is because of this SourceGenerated Code so MapView is now a namespace and therefore I have to specifiy more to say I want the MapView Control

```
using System;
namespace Mapsui.Samples.Maui.MapView
{
    public static class Samples
    {
        // Avoid double registration
        private static bool _registered;
        
        public static void Register() 
        {
            if (_registered)
                return;
                
            _registered = true;
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.PolylineSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.CircleSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.MyLocationSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.PinSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.PolygonSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.ManyPinsSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.AnimatedMyLocationSample());
            Mapsui.Samples.Common.AllSamples.Register(new Mapsui.Samples.Maui.SnapshotSample());

        }
    }
}
```

2024-01-22 22:37 UTC, inforithmics commented on Mapsui.Nts/GeometryFeature.cs
> +        FeatureExtensions.RegisterFeature<GeometryFeature>(f => new GeometryFeature((GeometryFeature)f));
The Copy Feature does not work. But this Code is now created by a Source Generator so no need to do it by hand.

2024-01-22 22:40 UTC, inforithmics commented on Mapsui/Extensions/FeatureExtensions.cs
> +        return (IFeature)Activator.CreateInstance(type, feature)!;
This shouldn't happen, because I wrote a Source Generator that creates a static Constructor in which the Custom Feature gets registered. So that the Copy works for CustomFeatures to. I tested the Source Generator for Types that are already in Mapsui.
Writing this I discovered that I don't Source Generate for Features that inherit from another feature for example PointFeature the Copy does not work.

2024-01-22 22:45 UTC, inforithmics commented on Mapsui/Extensions/FeatureExtensions.cs
> +        return (IFeature)Activator.CreateInstance(type, feature)!;
I wrote this code I don't know if I can ask if I'm in AOT Mode, and return (IFeature)Activator.CreateInstance(type, feature)!; Could still work but is not guaranteed in AOT Mode.

```
try
{
    // Fall Back if Type is not registered
    var type = feature.GetType();
    return (IFeature)Activator.CreateInstance(type, feature)!;
}
catch (Exception ex)
{
    Logger.Log(LogLevel.Error, ex.Message, ex);
    throw new NotSupportedException($"Register {feature.GetType().Name} so that it works in AOT Mode");
}
```

2024-01-25 08:27 UTC, pauldendulk commented on Mapsui/Extensions/FeatureExtensions.cs
> +        return (IFeature)Activator.CreateInstance(type, feature)!;
I think that this is an acceptable fix. As soon as an inherited feature is introduced in AOT mode the user sees the error (when running in debug mode).

I think we should think about the need to copying in general. It would also be the responsibility of the user to implement a copy function. Or perhaps we should remove the need for copying entirely. We need copying at the moment in projecting and editing. There may be other ways to deal with this. 

Is there any other reason why the PR is WIP? Is don't see an objection to merge.

2024-01-25 08:27 UTC, pauldendulk commented on Samples/Mapsui.Samples.MapView/AnimatedMyLocationSample.cs
> +    private UI.Maui.MapView? _mapView;
"so MapView is now a namespace", I don't understand why, but maybe I need to learn more about source generators.

2024-02-07 22:03 UTC, inforithmics commented
Things done:
I use now ICloneable to Clone a Feature so a Custom Feature needs to implement IClonable for copying

2024-02-07 22:25 UTC, inforithmics commented
> I have one question left, and one remark about adding an exception. If fixed I will merge this asap.

It is done now with IClonable so no need for an exception

2024-02-10 07:37 UTC, pauldendulk approved these changes
Good decision to revert the source generators. It is always hard to make such a decision if you have already invested in that solution. The downside of ICloneable is that users have to implement it if they want to add a custom feature. That ix some work they need to do, but it also clear.

2024-02-10 07:37 UTC, pauldendulk commented on Mapsui/Layers/AnimatedLayers/AnimatedPointFeature.cs
> +    public AnimatedPointFeature(AnimatedPointFeature animatedPointFeature) : base(animatedPointFeature)
I like that you still implement the copy constructor although the main purpose is to implement ICloneable.

2024-02-10 07:37 UTC, pauldendulk commented on Mapsui/Extensions/FeatureExtensions.cs
> -        return (T)Activator.CreateInstance(typeof(T), original)!;
Activator.CreatInstance is now fully removed here. Good, it was problematic in other situations as well.

Doing a search on the code base I see there is still a Activator.CreatInstance in GradientTheme. Not used a lot but we use it in the ShapefileSample. What will users experience when they try to use it in Blazor AOT? I guess we can find out soon. For me it is important that the user understands what is going on. We do not have to fix all the scenarios. Let't not implement ICloneable for style. Perhaps we will convert all styles to records some day to get this functionality for free.

2024-02-10 07:38 UTC, merged

2024-02-10 08:36 UTC, inforithmics commented
I plan to do 2 follow up pull requests
1. Remove Activator from GradientTheme
2. Remove IDisposable from Map/Layer

2024-02-10 08:58 UTC, pauldendulk commented
Please create issues to discuss a possible solution. 

In the case of number 2 I think this could be a really big change which we should be preceded by a number of smaller PRs that prepare for it.

2024-02-10 10:13 UTC, pauldendulk commented
Here is an issue about making the Map non-disposable. https://github.com/Mapsui/Mapsui/issues/2372