Fix: Blazor HttpClientHandler.Credentials
Mapsui/Mapsui pull request #2574
Opened 2024-03-30 20:47 UTC by inforithmics

Looking through the Code I found some instances where the Credentials were set for The HttpClientHandler without a try catch
NotSupportedException, this is necessary for Blazor because Blazor does not support hits.

2024-03-31 00:43 UTC, inforithmics commented
In the process of fixing the WFS Point sample I discovered a caching Bug. I only cache the url but not depending on the post data, which is important because there the parameters are written

2024-04-01 16:43 UTC, pauldendulk commented
ah, it is important to fix this kind of thing and to be clear about what we support. What will the user experience be when users selects the 'wms called tiles' sample in Blazor?

2024-04-02 08:35 UTC, inforithmics commented
The user experience is that it works now. But the wms called tiled and wets sample didn’t work on other platforms either because, the wms and wets adresses changed.

2024-04-03 06:24 UTC, pauldendulk commented
> The user experience is that it works now. 

ah, that is a nice feature 😁

> But the wms called tiled and wmts sample didn’t work on other platforms either because, the wms and wmts addresses changed. The platform not supported fix is a Blazor specific fix.

In the current Blazor sample just nothing happens, that is not good. In debug you see an error, that's better. I think we should turn on error logging in map in our samples. Perhaps just all logging, if that is useful for the samples.

I don't see the 'ArcGIS dynamic' sample in the WPF sample. Do you happen to know why that is?

Note, better error messages should not be a part of this PR, but this is a situation where we should investigate this.

2024-04-03 15:57 UTC, inforithmics commented
That the sample isn't displayed in wpf I have to investigate. Have you tried a rebuild all after getting the Source Code. Could Be that the SourceGenerator that creates the sample calling Code wasn't run.

2024-04-03 16:13 UTC, inforithmics commented
I tried the wpf Sample and for me it displayed the dynamic Arcgis sample. You have to wait some time because it is not the fastest service.

2024-04-04 21:16 UTC, inforithmics commented
I'm still investigating why the wfs sample does not work in blazor. I progressed one step further.
1. If the Wfs service is asked with https:// for capabibilites other calls are expected to be called with https:// too or else it fails in blazor. (CORS)
2. Currently the wfs post for getting the points does not work yet in blazor, it works in wpf or other targets.

2024-04-08 11:18 UTC, pauldendulk requested changes
I have a few questions and propose to throw and not accept null in the uri scheme extensions.

2024-04-08 11:18 UTC, pauldendulk commented on Mapsui/Extensions/StringExtensions.cs
> +    public static string? UriScheme(this string? url)
I think it is better to call the GetUriScheme.

2024-04-08 11:18 UTC, pauldendulk commented on Mapsui/Extensions/StringExtensions.cs
> +            return null;
In general is better to throw early when something it happening that you do not expect. I don't understand the situation fully, but it seems to me here it would be better to always throw when the scheme can not be determined. If you know of a situation where it could not be determined then we need to discuss how to deal with it. If we both don't know when we should accept null but there is a real case where we should accept null than it is still be to throw now that we do not know and then think of a better solution when we find out.

2024-04-08 11:18 UTC, pauldendulk commented on Mapsui/Extensions/StringExtensions.cs
> +        if (string.IsNullOrEmpty(scheme) || string.IsNullOrEmpty(url))
Here too I think we should throw instead of return null. Also don't accept null instead there is a good reason for it.

2024-04-08 11:18 UTC, pauldendulk commented on Samples/Mapsui.Samples.Common/Maps/DataFormats/WfsPointsSample.cs
> +        provider.GetFeatureGetRequest = true;
What does GetFeatureGetRequest do? What went wrong without this line?

2024-04-08 18:03 UTC, inforithmics commented on Mapsui/Extensions/StringExtensions.cs
> +    public static string? UriScheme(this string? url)
Done

2024-04-08 18:07 UTC, inforithmics commented on Mapsui/Extensions/StringExtensions.cs
> +            return null;
I throw now exceptions when the schema is not valid

2024-04-08 18:09 UTC, inforithmics commented on Mapsui/Extensions/StringExtensions.cs
> +        if (string.IsNullOrEmpty(scheme) || string.IsNullOrEmpty(url))
i throw now exceptions

2024-04-08 18:35 UTC, inforithmics commented on Samples/Mapsui.Samples.Common/Maps/DataFormats/WfsPointsSample.cs
> +        provider.GetFeatureGetRequest = true;
what I thought I could implment is a fallback on GetFeatureGetRequest when the post request does not work.

2024-04-08 18:55 UTC, pauldendulk commented on Samples/Mapsui.Samples.Common/Maps/DataFormats/WfsPointsSample.cs
> +        provider.GetFeatureGetRequest = true;
Okay, I have worked with CORS before but is not easy to see from that code that this solves that problem. In general my reasoning is that you should be able to understand what code is doing by reading it, and if you don't you are allowed to remove it to find out (sometimes much later) why it is there. But I understand that this is all based on very old code which can not be easily rewritten. So fine for now.

2024-04-08 20:31 UTC, pauldendulk approved these changes

2024-04-08 20:31 UTC, merged