WIP Upgrade: Uno to 5.2 and use single Project for Samples
Mapsui/Mapsui pull request #2609
Opened 2024-04-25 22:28 UTC by inforithmics

I upgraded to Uno 5.2 and use the new single Project Infrastructure for the Sample, All platforms are now in one project like maui. The WinUI target starts the other I haven't tested yet.

2024-04-29 07:49 UTC, pauldendulk requested changes
This is a great improvement. Lots of files removed. I have a few remarks and questions to look at.

2024-04-29 07:49 UTC, pauldendulk commented on Mapsui.UI.WinUI/Globals.cs
> +﻿global using System;
I don't like the use of Global.cs in Mapsui because we deal with many different namespaces and I like to know exactly what is used by looking at the usings. Namespace conflict can become extremely hard to understand when using globals. Although it may not be such a problem within the scope of this project I think it is just more clear to use Global.cs nowhere. Also the benefit here is very small, it affects only one class.

2024-04-29 07:49 UTC, pauldendulk commented on Mapsui.UI.WinUI/MapControl.cs
> -// Copyright (c) The Mapsui authors.
I think you deleted this line by accident.

2024-04-29 07:49 UTC, pauldendulk commented on Samples/Mapsui.Samples.Uno.WinUI/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
Why a .gitignore is added at this level? We are in a cleanup phase and I would like to remove all the files we do not need, or do not understand. There may be a good reason to add it here but I like to understand why. Is there not a lot of overlap with the root one? Could what's in here not be added the root one? What worries me is if we add it here, why not in all other samples? I want to keep fighting against unnecessary growth of the repository.

2024-04-29 07:49 UTC, pauldendulk commented on global.json
> +  "msbuild-sdks": {
Why was this necessary. What step fails if this is not here?

2024-04-30 11:56 UTC, inforithmics commented on Mapsui.UI.WinUI/Globals.cs
> +﻿global using System;
I’ll try to fix this with conditional compilation. In the mapcontrol

2024-04-30 11:57 UTC, inforithmics commented on Mapsui.UI.WinUI/MapControl.cs
> -// Copyright (c) The Mapsui authors.
Thanks for finding this. Was a mistake

2024-04-30 11:58 UTC, inforithmics commented on Samples/Mapsui.Samples.Uno.WinUI/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
This came with the uno winui template will remove it

2024-04-30 11:59 UTC, inforithmics commented on global.json
> +  "msbuild-sdks": {
With the uno.winui mechanism this needs in the global.json. I’ll try to move it to the uno.winui samples folder.

2024-04-30 19:43 UTC, inforithmics commented on global.json
> +  "msbuild-sdks": {
I tried moving it to Winui folders but didn't succeed I guess it has really to be in the global.json file and there can only be one at the root.

2024-04-30 19:47 UTC, inforithmics commented
@pauldendulk I adressed the comments, the  "msbuild-sdks":  I couldn't move downwards it really needs to be in the global.json file this value is used read by Uno to make make the single project work. It provides the Version Number for all Uno components.

2024-05-02 05:43 UTC, pauldendulk commented on Mapsui.UI.WinUI/Globals.cs
> +﻿global using System;
oh, I think I do not understand the reason for the Global.cs. I thought it was just to have to include less usings, what needs to be fixed?

2024-05-02 05:45 UTC, pauldendulk commented on global.json
> +  "msbuild-sdks": {
No problem, I just need to understand these kind of things because they will need updating at some point.

2024-05-02 06:02 UTC, pauldendulk approved these changes
All great. I like all the cleaning up done in the later commits.

2024-05-02 06:04 UTC, pauldendulk commented on Mapsui.UI.WinUI/Globals.cs
> +﻿global using System;
ok, so, they are really conditionally needed. I prefer the #if over Globals.cs. Fine like this.

2024-05-02 06:04 UTC, merged

2024-05-02 16:59 UTC, inforithmics commented on .github/workflows/dotnet.yml
> +        fetch-depth: 1
Yes but I had to revert it because package with checkin hash needs history. Until the last version tag.