Feature: BitmapPath
Mapsui/Mapsui pull request #2611
Opened 2024-04-26 21:38 UTC by inforithmics

Implements this

2024-04-30 16:13 UTC, pauldendulk commented
> * Instead of IconPath I used the name BitmapPath (Consistency because the id is called BitmapId)

Good choice to be consistent. Yet we may have to rename the BitmapId as well, because it is not just a bitmap, but can be svg or SKPicture as well. But this might change entirely.

> * I Added a Bitmap Registry to the RenderService it is called RenderBitmapRegistry, it records all Bitmaps that are registred during the rendering and when the RenderService is disposed the Regisered Images are unregistered and disposed. So that no Memory Leaks can occur.

Good, it is important to have clear who is responsible for disposing. The general rule that we had in C++ and Delphi is that the class creating the instance is responsible for disposing it. That is a good simple rule. That rule is also used by the dispose analyzer we use. In our code we do not always apply this rule and I think we can fix that so that we do not have to suppress warnings (but there may be exceptions). In the case of caches objects exist over a longer period and it is not possible to create & dispose within a small scope. In that case the cache should be responsible for disposing, but thus also for creating. We often create on the outside and then put is in the cache which forces us to suppress a warning. Instead we should pass in a create method to the cache. I don't think that should be part of this PR.

2024-05-02 08:15 UTC, pauldendulk requested changes
I have a few remarks and please could you look at the warnings in the files changed page.

Other than the main problem is that the symbols now depend on the data not available in the definition, which is a consequence of the initial proposal. 

We talked about tree step rendering (1. convert to skia. 2. draw on canvas), we do not have that yet. But we have the distinction between data fetching (in the providers) and rendering. With the bitmapPath setup the symbols need a similar distinction. Lets not try to fix that in this PR.

2024-05-02 08:15 UTC, pauldendulk commented on Tests/Mapsui.Tests/Styles/BitmapRegistryTests.cs
> +        renderRegistry.Dispose();
Dispose is called here to dispose the items in the cache, but next the renderRegistry which was just disposed is called to check if a key exists. As a user I would expect an exception when calling a disposed object. Perhaps we need to add a Clear() method which also disposes the items in the cache (it should because the cache is responsible for the dispose).

2024-05-02 18:52 UTC, inforithmics commented on Mapsui.Rendering.Skia/Cache/RenderBitmapRegistry.cs
> +public class RenderBitmapRegistry(BitmapRegistry instance) : IBitmapRegistry
fixed it

2024-05-02 19:02 UTC, inforithmics commented on Mapsui.Rendering.Skia/Cache/RenderService.cs
> +        VectorCache = new VectorCache(this, capacity);
I think I should do this operation on an InitializeAsync()  that is called before the first render.

2024-05-02 19:30 UTC, inforithmics commented on Tests/Mapsui.Tests.Common/Maps/BitmapBitmapPathSymbolSample.cs
> +        var circleIconPath = typeof(BitmapBitmapPathSymbolSample).LoadBitmapPath("Resources.Images.circle.png");
is now fixed, I moved all Bitmap Path samples in the BitmapPath category

2024-05-02 19:40 UTC, inforithmics commented on Tests/Mapsui.Tests/Styles/BitmapRegistryTests.cs
> +        renderRegistry.Dispose();
Improved unit test throw a disposed exception when RenderBitmapRegistry is disposed

2024-05-02 19:57 UTC, inforithmics commented on Mapsui.Rendering.Skia/Cache/RenderService.cs
> +        VectorCache = new VectorCache(this, capacity);
Yes you are right this should be a follow up pull request.
I think there should be an InitAsync(IRenderService renderService) Method on Styles and ILayer and this is called before the first render. But this would case a lot of code changes making this pull request to large.

2024-05-02 19:59 UTC, inforithmics commented on Mapsui.Rendering.Skia/Cache/RenderBitmapRegistry.cs
> +    public object? Unregister(int id)
Good point, Currently it is everything that is in BitmapRegistry. So no differentiation here yet.

2024-05-04 05:29 UTC, pauldendulk commented on Mapsui.Rendering.Skia/Cache/RenderService.cs
> +        VectorCache = new VectorCache(this, capacity);
I would like to keep the styles simple value objects. Perhaps they should be immutable. 

The big picture I am trying to work towards is to limit or isolate the code that could cause trouble: mutating state, locking,  disposing, async-await, caching, threading. We do need all that but I want to keep most of our code simple, preferring immutable data and pure function to operated on it. The problematic code should be on the surface of the architecture, the simple code in the core and should not depend on potential problematic code.  That is why I want to fetching to be removed from the the layers. The definition of the map should be just a description that could be easily serialized. The styles are part of that description.

Fetching the data for the styles is like fetching data of the providers, but I am not yet happy with how that works for layers and providers. So, I don't have plan ready yet. Let me think about it a bit more.

2024-05-04 07:37 UTC, charlenni commented on Mapsui.Rendering.Skia/Cache/RenderService.cs
> +        VectorCache = new VectorCache(this, capacity);
As I said before: Remove BitmapRegistry from Mapsui and add a Source or ImageSource URL to SymbolStyle. This is used in the renderer to retrieve the image data. The renderer is also responsible for caching this data. With this, the user didn't has to register the bitmap/image and the renderer could handle the image data with all its knowledge about the formats (sprites as part of a bigger bitmap, SVG with changing colors and so on).

Perhaps there can be providers for the different schemes which are registered like the different renderers. There can be one, knowing how to get a http source or a file source. But you can add additional providers for special, owner defined schemes too. Can be a 'base64', which converts from a base64 coded string to a drawable object, or a 'svg-color' scheme, which creates a drawable object from a SVG with changing one of the colors.

That approach is flexible and easily extendible without changing the code of Mapsui. The user has the possibility to extend the code.

With this, we have in Mapsui.Styles.SymbolStyle only a ˋˋˋURL ImageSourceˋˋˋ and in the renderer a cache with ˋˋˋDictionary<URL, SKPicture>ˋˋˋ. The renderer checks, if the URL is in the cache and if not, it retrieves the provider for this scheme from the list and ask for the SKPicture. Because this is a longer operation, the symbol isn't drawn in the first run, but if the SKPicture is ready, a redraw is started. Then the URL should be in the cache.

2024-05-04 07:55 UTC, pauldendulk approved these changes

2024-05-04 07:55 UTC, pauldendulk commented on Mapsui.Rendering.Skia/Cache/RenderBitmapRegistry.cs
> +        if (_createdImages == null) throw new ObjectDisposedException(nameof(RenderBitmapRegistry));
I would prefer a 'disposed' boolean, it is a very common thing to do in dotnet. But I am not even sure if we should do this at all. If we add it here should we add a disposed boolean to all the classes that have a IDispose and should we have a `if (dispose ) throw new ObjectDisposedException(nameof(MyClass));` line at the top of every single method of those classes? My original question came up because it look weird if you Dispose a class and call that same class in the lines after it. I don't know the best solution. Lets leave it like this for now.

2024-05-09 11:10 UTC, pauldendulk commented
Tomorrow I will investigate splitting out the SKPicture from the BitmapRegistery.

2024-05-09 11:10 UTC, merged

2024-05-09 13:11 UTC, inforithmics commented on Mapsui.Rendering.Skia/Cache/RenderBitmapRegistry.cs
> +        if (_createdImages == null) throw new ObjectDisposedException(nameof(RenderBitmapRegistry));
I'll adress this in my next pull request

2024-05-09 13:12 UTC, inforithmics commented on Mapsui.Rendering.Skia/Cache/RenderService.cs
> +        VectorCache = new VectorCache(this, capacity);
I'll think I'll try to implement this idea in my next pull request. So that the BitmapRegistry isn't pulluted with SkPicture instances.

2024-05-10 05:07 UTC, pauldendulk commented on Mapsui.Rendering.Skia/Cache/RenderBitmapRegistry.cs
> +        if (_createdImages == null) throw new ObjectDisposedException(nameof(RenderBitmapRegistry));
How do you want to resolve it? The best solution I can come up with is to do it like it was originally. So, no ObjectDisposedException and field to track the disposed state. If we want an exception we have to add checks everywhere and I am we should try to reduce clutter. The important thing is that the disposable objects in the class are actually disposed. The only thing I would change is to rewrite te unit test so that it does not need to call a class after it is disposed.

2024-05-10 05:18 UTC, pauldendulk commented on Mapsui.Rendering.Skia/Cache/RenderBitmapRegistry.cs
> +        if (_createdImages == null) throw new ObjectDisposedException(nameof(RenderBitmapRegistry));
oh, you already have a new PR. Well, it looks clean like this, so fine. But this should not be necessary many classes.