WIP Feature: Gpu Acceleration for Uno
Mapsui/Mapsui pull request #2630
Opened 2024-05-10 22:16 UTC by inforithmics

Added UseGpu to Uno so that it can run on Gpu on Android, Wasm and iOS

2024-05-10 22:26 UTC, charlenni commented on Mapsui.UI.WinUI/MapControl.cs
> +#if HAS_UNO_WINUI
The idea behind UseGPU was to select CPU or GPU while runtime. If you set UseGPU before creating MapControl, then it would select the right view. If you do it by your way, you have to select it at compiletime.

2024-05-10 22:40 UTC, inforithmics commented on Mapsui.UI.WinUI/MapControl.cs
> +#if HAS_UNO_WINUI
This line is here to remove this code from the WinUI target. Because the Code is shared here with Uno.

The Conditional Compiliation is used only for setting the default values of useGpu.
Currently it is supported in Android iOS and WebAssembly on Windows it isn't supported yet.

2024-05-11 05:19 UTC, charlenni commented on Mapsui.UI.WinUI/MapControl.cs
> +#if HAS_UNO_WINUI
But this isn't correct. You use the conditional compilation also for adding code. Eg. in this case you add or remove the code for invalidation of the GPU view by conditional compilation and not by checking the flag UseGPU. This makes it harder to add the functionality later.

2024-05-14 16:12 UTC, inforithmics commented on Mapsui.UI.WinUI/MapControl.cs
> +#if HAS_UNO_WINUI
You are right, I have changed the Code now can you have again a Look at it.

#if HAS_UNO_WINUI is used for code that is only valid in Uno.Winui because the Control is shared between Uno.WinUI and WinUI.

2024-05-20 06:33 UTC, pauldendulk requested changes
Great work. I have one remark wrt the #ifs

2024-05-20 06:33 UTC, pauldendulk commented on Mapsui.UI.WinUI/MapControl.cs
> +        if (UseGPU)
The `#if`s make the code hard to read. The indentation problem makes it worse. I propose to keep the UseGPU field outside the `#if` scope so that it is available on all platforms and would throw an exception if not available. The main code would be the same. Also from the users perspective this may be better, the exception can inform the developer. I was already considering moving UseGPU to the shared project so that it is available everywhere (but not implemented everywhere).  

Perhaps there are also other ways to rewrite this to reduce the invasiveness of the `#if`s. The way things is split up in methods may need to be altered. The main code should be easy to read, the different implementations should be some differences in the details.

2024-05-20 15:25 UTC, pauldendulk commented on Mapsui.UI.Uno.WinUI/SKSwapChainPanel.cs
> +#if !HAS_UNO_WINUI
It's a lot better like this!

2024-05-20 15:25 UTC, pauldendulk approved these changes

2024-05-20 15:25 UTC, merged