WIP ios Uno Investigation: https://github.com/Mapsui/Mapsui/issues/2638
Mapsui/Mapsui pull request #2640
Opened 2024-05-19 21:23 UTC by inforithmics

Added a sample that shows where the mouse is clicked.
Intrestingly at the top the click and the blue circle are almost the same but at the buttom the difference is greater. So it seems a screen point density problem.

2024-05-20 09:32 UTC, inforithmics commented on Samples/Avalonia/Mapsui.Samples.Avalonia.iOS/Info.plist
> +	<string>13.0</string>
Discovered that the min ios Version has changed to version 13

2024-05-20 15:30 UTC, pauldendulk requested changes
Not sure if you want to merge this, but if so try to fix the warnings.

2024-05-20 15:30 UTC, pauldendulk commented on Tests/Mapsui.Tests.Common/Maps/TouchPointSample.cs
> +    private static Map _map;
Why does the _map need to be static?

2024-05-20 15:30 UTC, pauldendulk commented on Tests/Mapsui.Tests.Common/Maps/TouchPointSample.cs
> +    private TextBoxWidget _label;
Not sure if you want this to be merged because it is mainly to show a bug. But if this is merged we should get rid of nullable and reassignment warnings.

2024-05-22 21:56 UTC, inforithmics commented on Tests/Mapsui.Tests.Common/Maps/TouchPointSample.cs
> +    private static Map _map;
fixed

2024-05-22 21:57 UTC, inforithmics commented on Tests/Mapsui.Tests.Common/Maps/TouchPointSample.cs
> +    private TextBoxWidget _label;
fixed

2024-05-24 07:09 UTC, pauldendulk approved these changes

2024-05-24 07:10 UTC, merged