GeometryCollection rendering fix
Mapsui/Mapsui pull request #2656
Opened 2024-05-27 13:31 UTC by IldarKhayrutdinov

## Fix for GeometryCollection rendering

### Befor
Filled LineString

![2024-05-27 15_28_37-Mapsui UI Avalonia](https://github.com/Mapsui/Mapsui/assets/29858598/4c28c45c-8da7-439f-85a2-95620390af5a)

### After

![2024-05-27 15_29_57-Mapsui UI Avalonia](https://github.com/Mapsui/Mapsui/assets/29858598/c4623aa9-be4f-4d68-85b7-81bdd3960ecc)

2024-05-27 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Mapsui/Mapsui?pullRequest=2656) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Mapsui/Mapsui?pullRequest=2656) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Mapsui/Mapsui?pullRequest=2656) it.</sub>

2024-06-03 15:10 UTC, pauldendulk commented
@IldarKhayrutdinov Thanks, I see you added tests and a sample, great. Could you take me along a bit into what you ran into? The original code used a GeometryCollectionRenderer and GeometryCollectionExtensions. These are not necessary anymore. That looks good, but what is the thinking behind this? I like to have a bit of context when reviewing.

2024-06-03 15:25 UTC, IldarKhayrutdinov commented
@pauldendulk I need to draw Collection = LineString with some control Points on line, they are drawn as filled polygons.

2024-06-08 21:33 UTC, inforithmics requested changes
This fixes a Bug that was probably introduced when GeometryCollectionRenderer was introduced. 

But for Performance reasons the ToPath Functions should have position in the tuple instead of the Geometry.

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/VectorStyleRenderer.cs
> +                        foreach (var child in collection)
The current implementation uses the Geometry for the caching key to make it more efficient it would be better to use the position in the Geometry Collection for caching.

```
for (var index = 0; index < collection.Count; index++)
{
    var child = collection[index];
    DrawGeometry(child, index);
}
```

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/VectorStyleRenderer.cs
> +                    PolygonRenderer.Draw(canvas, viewport, vectorStyle, feature, polygon, opacity, renderService.VectorCache);
Here
` PolygonRenderer.Draw(canvas, viewport, vectorStyle, feature, polygon, opacity, renderService.VectorCache, position);`

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/VectorStyleRenderer.cs
> +                    LineStringRenderer.Draw(canvas, viewport, vectorStyle, feature, lineString, opacity, renderService);
Here
`LineStringRenderer.Draw(canvas, viewport, vectorStyle, feature, lineString, opacity, renderService, position);`

2024-06-08 21:33 UTC, inforithmics commented on Samples/Mapsui.Samples.Common/Maps/Geometries/GeometryCollectionSample.cs
> +﻿using System.Collections.Generic;
Good Sample. I think that when I Introduced the GeometryCollectionRenderer I might have broken the Rendering of Different Geometries in a Geometry Collection so good Improvement,  to having a sample for that.

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/PolygonRenderer.cs
> +        SKPath ToPath((long featureId, Polygon polygon, MRect extent, double rotation, float lineWidth) valueTuple)
This should take the new position parameter, because the tuple in the ToPath is used as a cache key and comparing an int is much faster than comparing a polygon on equalness.
Because it is a local function the polygon is captured from the context so it isn't really needed in the parameter.

`SKPath ToPath((long featureId, int position, MRect extent, double rotation, float lineWidth) valueTuple)`

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/PolygonRenderer.cs
> +        using var path = vectorCache.GetOrCreatePath((feature.Id, polygon, extent, rotation, lineWidth), ToPath);
Should be calling position
`using var path = vectorCache.GetOrCreatePath((feature.Id, position, extent, rotation, lineWidth), ToPath);`

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/VectorStyleRenderer.cs
> +        void DrawGeometry(Geometry? geometry)
The position should be a parameter for the draw. So that FeatureId and Position are the unique key for the geometry, 0 is the default when no position is explicitly given. like for directyl rendering a LineString and Polygon.
`void DrawGeometry(Geometry? geometry, int position = 0)`

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/LineStringRenderer.cs
> +        SKPath ToPath((long featureId, LineString lineString, MRect extent, double rotation, float lineWidth) valueTuple)
Linestring should be position because it is used for caching and position is faster compared than linestring.
`SKPath ToPath((long featureId, int position, MRect extent, double rotation, float lineWidth) valueTuple)`

2024-06-08 21:33 UTC, inforithmics commented on Mapsui.Rendering.Skia/SkiaStyles/LineStringRenderer.cs
> +            using var path = renderService.VectorCache.GetOrCreatePath((feature.Id, lineString, extent, rotation, lineWidth), ToPath);
the position should be given.
`using var path = renderService.VectorCache.GetOrCreatePath((feature.Id, position, extent, rotation, lineWidth), ToPath);`

2024-06-11 22:00 UTC, inforithmics approved these changes
Good work

2024-06-14 21:19 UTC, merged