WIP: Feature: Mapsui for Window Forms
Mapsui/Mapsui pull request #2690
Opened 2024-06-22 09:20 UTC by inforithmics

Adds Windows Forms support.

2024-06-25 19:36 UTC, pauldendulk requested changes

2024-06-26 06:51 UTC, charlenni commented on Samples/Mapsui.Samples.WindowsForms/SampleWindow.cs
> +                _rotationSlider.Value = (int)((_mapControl.Map.Navigator.Viewport.Rotation + 360) % 360);
I would find it more confusing in a sample to use a special function from somewhere to do this instead of a easy understandable calculation.

For me it is the bigger problem, that I have to clamp the rotation between 0 and 360 by myself. But we discussed this elsewhere.

2024-06-26 06:56 UTC, charlenni commented on Mapsui.UI.WindowsForms/MapControl.cs
> +public partial class MapControl : UserControl, IMapControl, IDisposable
The Eto.Forms implementation has only a CPU backed canvas, where this implementation from Thomas has a CPU and GPU one. The GPU backend is so much faster than the CPU backend, that it is worth to use it.

Perhaps the Eto.Forms part could be redesigned in the this implementation works, but I'm not sure, if the is a GPU backend control of SkiaSharp for Eto.Forms.

One thing, that is solved better in the Eto.Forms implementation is the handling of cursors.

2024-06-26 07:01 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +using Timer = System.Threading.Timer;
As I see it, the Timer is used for redrawing the screen each 16 ms. So the Timer is certainly right in the shared code.

2024-06-26 07:06 UTC, charlenni commented on Mapsui.UI.Shared/MapControl.cs
> +using Timer = System.Threading.Timer;
Isn't there a second timer in the WinForms eco system, so that it you have to define, which one do you want to use. But if there is only one timer in the others, you have to do this only for WinForms. So there are two possibilities:
1. Use it as a full definition like System.Threading.Timer
2. Define it in the usings as Thomas made it.

2024-07-07 14:27 UTC, inforithmics commented on Mapsui.UI.WindowsForms/MapControl.cs
> +public partial class MapControl : UserControl, IMapControl, IDisposable
Eto.Forms and WindowsForms are technology wise quite different. (Something like Windows forms and Xamarin.Forms have only the Name Forms in the name) But I agree that some parts could be shared more but I think this should be a different Pull request to keep the changes small.

2024-07-07 14:29 UTC, inforithmics commented on Mapsui.UI.Shared/MapControl.cs
> +using Timer = System.Threading.Timer;
Then I make the Timer name fully qualified to reduce the using statements, maybe in a future version we could move the namespace of all mapcontrols to Mapsui.UI so not needing this usings #ifdef block

2024-07-07 14:32 UTC, inforithmics commented on Samples/Mapsui.Samples.WindowsForms/SampleWindow.cs
> +                _rotationSlider.Value = (int)((_mapControl.Map.Navigator.Viewport.Rotation + 360) % 360);
I'm using the NormalizeRotation Function so that viewers of this sample see the available Functionality of Mapsui

2024-07-07 14:32 UTC, inforithmics commented
@pauldendulk can you review the changes?

2024-07-07 15:01 UTC, charlenni commented on Samples/Mapsui.Samples.WindowsForms/SampleWindow.cs
> +                _rotationSlider.Value = (int)((_mapControl.Map.Navigator.Viewport.Rotation + 360) % 360);
That doesn't work. Rotation could in Mapsui getting magazine with values higher than 360 (e.g. -425). So you have to make the modulo 360, add 360 and make another modulo 360.

2024-07-13 19:41 UTC, inforithmics commented
Things done:
1) Added Getting startet.
2) Added nuget to Readme

2024-07-15 12:19 UTC, merged

2024-07-15 12:20 UTC, pauldendulk commented
Thanks @inforithmics and @charlenni

2024-07-16 22:23 UTC, jkhoel commented
@pauldendulk Will there be a nuget package available for this?

2024-07-17 07:16 UTC, pauldendulk commented
Yes, with the release of 5.0.0-beta.3.