Feature: Render to Jpeg with Quality Setting.
Mapsui/Mapsui pull request #2813
Opened 2024-11-26 19:49 UTC by inforithmics

GetSnapshot can now render to jpeg with Quality setting

2024-12-08 18:18 UTC, pauldendulk requested changes
Great, I have two small remarks.

2024-12-08 18:18 UTC, pauldendulk commented on Tests/Mapsui.Rendering.Skia.Tests/TestRenderFormats.cs
> +    public async Task TestSameOutputJpegGetsSmallerWithLessQuality()
Here the Async suffix should be added. And the test below as well.

2024-12-08 18:31 UTC, inforithmics commented on Mapsui.Rendering.Skia/MapRenderer.cs
> +                            new SKWebpEncoderOptions(SKWebpEncoderCompression.Lossy, quality);
fixed

2024-12-09 06:01 UTC, pauldendulk approved these changes

2024-12-09 06:02 UTC, merged